### ISSUE TITLE
CRLF across 8k boundary inserts an empty line

### ISSUE THREAD

**Issue by monnerat** [mate-desktop/pluma#100]
Originally reported for Fedora 20 at https://bugzilla.redhat.com/show_bug.cgi?id=1166178
Use the attachment at https://bugzilla.redhat.com/attachment.cgi?id=959378 for tests.
Thanks for investigating.
Best regards.
<quote>
Description of problem:
When editing a file with CRLF line ends (DOS), a CRLF across a 8K boundary causes an empty line to be inserted.

Version-Release number of selected component (if applicable):
pluma-1.8.1-2.fc20.x86_64

How reproducible:
Always

Steps to Reproduce:
1. Get the crlfs.txt file in attachment (it does not contain empty line).
2. Edit it with pluma.
3. Browse to the last line: remark it is preceded by a empty line that was not in the initial file.

Actual results:
As mentioned.

Expected results:
No insertion of empty line.
</quote>

**Comment by sleeveroller** [comment]
I can reproduce this issue on Debian Sid - Pluma 1.8.1.

I did some investigation and it seems Pluma reads files in 8k chunks and adds each chunk individually to the gtk text control which tries to tidy up the data as it's added.

When the 2 byte end of line is split on the 8k boundary the gtk control sees the CR at the end of one chunk and the LF at the start of the next chunk as 2 newline indicators.

I don't know enough about the gnome or mate projects to say whether this is a bug in Gtk or in Pluma.

This [patch](https://gist.github.com/sleeveroller/5488bb2414cfd078be80#file-pluma-issue-100-patch) corrects this issue. It's a little hack basically so I haven't created a pull request. But it might serve as a pointer for someone to do a proper fix.

**Comment by monnerat** [comment]
@sleeveroller: thanks for your hint and your work on it. This helped me to produce a cleaner fix. The major difference with your hack is: the carriage return is not stripped, but its processing is delayed as a prefix to the next buffer.

**Comment by raveit65** [comment]
closed via https://github.com/mate-desktop/pluma/pull/148
