### ISSUE TITLE
org.mate.pluma.gschema.xml schema not installed and considered invalid

### ISSUE THREAD

**Issue by willysr** [mate-desktop/pluma#107]
Hi

I got a report (and confirmed in slackware-current as well) that several MATE packages are no longer works (though they built properly) due to schemas were invalid.

Here's a typical message when binaries are executed in terminal
(pluma:13552): GLib-GIO-ERROR **: Settings schema 'org.mate.pluma' is not installed

The real error message can be seen when executing post-installation scripts
/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
/usr/share/glib-2.0/schemas/org.mate.pluma.gschema.xml: Error on line 7 char 31: attribute 'xml:lang' invalid for element 'summary'.  This entire file has been ignored.

Since this is the same Slackware version that MATE 1.8 is being built on, i can say that this is a showstopper.

**Comment by ryanpcmcquen** [comment]
+1

**Comment by wazoox** [comment]
I've used this horrible hack and it works fine:

`for F in org.mate.dictionary.gschema.xml org.mate.disk-usage-analyzer.gschema.xml org.mate.eom.gschema.xml org.mate.screenshot.gschema.xml
do 
grep -v  xml:lang $F > /tmp/$F
sudo mv $F $F.orig
sudo mv /tmp/$F .
 done
`

**Comment by willysr** [comment]
Thanks. That does fix it
marking it solved now
