### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by blisbell** [mate-desktop/pluma#114]
http://pastebin.com/0KXyqM5V
This is where it dies on building on arch linux using http://pkgbuild.com/~flexiondotorg/mate-unstable-dual/1.9/x86_64/PKGBUILD/pluma-gtk3/  to build.

**Comment by blisbell** [comment]
I got this to build by removing this line in pkgbuild --enable-gtk-doc \

**Comment by monsta** [comment]
@flexiondotorg: distro-specific issue, can be closed I guess.
