### ISSUE TITLE
Put line numbers inside "View" tab

### ISSUE THREAD

**Issue by NeoTheFox** [mate-desktop/pluma#128]
![Screen](http://i.imgur.com/ITy69TH.png)

So this is what I propose - can you please put a line number option inside "View" tab? This way it is fast to turn line numbers on-off, dependent on what you are doing.
##

**Comment by infirit** [comment]
My initial thought is that this should be done through a plugin.

**Comment by sc0w** [comment]
pluma has line numbers on preferences:

http://i.imgur.com/VE3iRBC.png

I think on "view" tab is a good idea, and a shortcut keys too

**Comment by Yetoo1** [comment]
Would the option be redundant in the view tab and in the Pluma preferences or would it be switched around?

**Comment by raveit65** [comment]
To have it in both seems a bit overdosed for me.
Well, in menus a keyboard shortcut  can be added, which is the fastest way to use it.
