### ISSUE TITLE
Memory leak when switching GTK2 themes

### ISSUE THREAD

**Issue by equeim** [mate-desktop/pluma#139]
Memory usage increases by several MiB each time when I switch GTK2 theme in XFCE Appearance Settings.
This happens only with Pluma both with 1.8.1 and 1.10.2 versions.
Distro: Gentoo GNU/Linux.
##

**Comment by monsta** [comment]
I can't reproduce this with latest Pluma. I don't have Xfce though, so I used ```mate-appearance-properties``` to switch the themes several times. Memory usage of Pluma didn't increase.

Does it still happen for you with 1.14 or 1.16 versions?

**Comment by monsta** [comment]
Since Pluma is migrated to GTK+3 only code in version 1.17, this issue isn't relevant anymore.
