### ISSUE TITLE
add ability to use middle mouse button to close tabs

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#143]
Feature request:

To use middle button to close tabs, like firefox.

thanks

**Comment by sc0w** [comment]
This feature was implemented in caja:

The issue:
https://github.com/mate-desktop/caja/issues/457

The pull requests:
https://github.com/mate-desktop/caja/pull/497
https://github.com/mate-desktop/caja/pull/499

It can be adapted to pluma?

**Comment by raveit65** [comment]
merged https://github.com/bl0ckeduser/pluma/commit/18da32e2aca3578179bc90f99f2526097f09637f
