### ISSUE TITLE
GTK+3: port to libpeas, re-add Python plugin support

### ISSUE THREAD

**Issue by monsta** [mate-desktop/pluma#147]
This is just a reminder since we apparently have no report on that yet.

Currently Pluma has to be built without python support for GTK+3 as python support relies on pygtk.
Gotta fix that.
##

**Comment by raveit65** [comment]
also builtin python plugins doesn't work and try to enable them closes pluma immediately.
For fedora rawhide i switched to gtk3 an disable the plugins, see
http://pkgs.fedoraproject.org/cgit/pluma.git/diff/pluma_diasable-python-plugins.patch

**Comment by willysr** [comment]
Should be closed by now as it has been ported to libpeas in 1.17

**Comment by monsta** [comment]
Not yet, I still need to port Python plugins to libpeas (https://github.com/mate-desktop/pluma/pull/205 took care of C plugins only).

**Comment by monsta** [comment]
Almost there... only snippets plugin is left - it needs some more work. Currently the code completion there doesn't work at all, I could use some help with it I guess.

**Comment by monsta** [comment]
Ok, snippets are finally in. :slightly_smiling_face:
