### ISSUE TITLE
[FEATURE REQUEST, GTK3] Use header bar (Client side decorations)

### ISSUE THREAD

**Issue by adam900710** [mate-desktop/pluma#149]
Although pluma is meant to keep the old style of GTK2 version gedit, but there maybe people interested in using gtk3 header bar(Client side decorations).

GNOME3 devs have done a lot of stupid decisions, like dropping background transparent for gnome-terminal, dropping compact view for nautilus.
But there is still some good idea, at least for gtk3 header bar.

It provides quite a clean and focus layout, but still tweakable.
Just see the screenshot of them with default config.
![_2015-10-14_17-08-55](https://cloud.githubusercontent.com/assets/460269/10479329/53a473f4-7296-11e5-8be0-998e5ead083b.png)

Even disable all possible items, pluma still shows less content, even compared to the default setting of gedit.
![_2015-10-14_17-09-43](https://cloud.githubusercontent.com/assets/460269/10479337/62d36862-7296-11e5-9be9-8f5257074e2d.png)

So, it would be quite nice if pluma(and Mate) can use GtkHeaderBar to provide a much simple UI.

Thanks

**Comment by raveit65** [comment]
We all hate headerbars :)
and we love menus with full content.
That style is the reason why most people use mate.
