### ISSUE TITLE
Pluma does not support Scala syntax highlighting

### ISSUE THREAD

**Issue by rabinnh** [mate-desktop/pluma#152]
As the title says.  I am running Ubuntu 14.04 with these Pluma packages installed:

    ii  pluma                                                       1.8.1+dfsg1-2~ppa1~trusty1                          amd64             official text editor of the MATE desktop environment
    ii  pluma-common                                                1.8.1+dfsg1-2~ppa1~trusty1                          all          official text editor of the MATE desktop environment (common files)

I installed Gedit and it does support Scala syntax highlighting.

**Comment by monsta** [comment]
It's a limitation of GTK+2 version of ```gtksourceview```. We can't fix it here.

If you wish, you can ask the maintainers of [gtksourceview2](http://packages.ubuntu.com/source/trusty/gtksourceview2) to make a patch from [this commit](https://git.gnome.org/browse/gtksourceview/commit/?id=efc8a9f8750fbe92f4362edde8c778b571a2f460).
