### ISSUE TITLE
Gtk3 tracking report

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/pluma#154]
This report list only Gtk3 bugs which needs to be fixed before pluma can use for production with gtk3.
Please open a single report first if you found a new issue, mention there that you think this is a blocker report, and we will add them here.

MUST:

SHOULD:
- GTK+3 build has no python plugins support
  https://github.com/mate-desktop/pluma/issues/147

NICE TO HAVE:
##

**Comment by monsta** [comment]
Well, it's all done in 1.18.
