### ISSUE TITLE
Cannot build with gtk3 and mate-desktop support

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/pluma#156]
Beginning with pluma1.12.0 from git master on Nov 21, 2015, building Pluma fails unless --without-matedesktop is used in the build configuration. The build errors out with an inability to find mate-aboutdialog.h which in my builds is installed in /usr/include/mate-desktop-2.0/libmate/desktop/ .
Previous versions of Pluma buit without issue, so it looks to me like the new configuration option introduced an error when mate-desktop support is used, at least in gtk3 builds. I have not tested with gtk2 as I only have a gtk3 MATE build environment set up.

**Comment by monsta** [comment]
Oops...
Should be fixed in https://github.com/mate-desktop/pluma/commit/125169f8cb0ee1d06179a3769fe3368b5df35527.
