### ISSUE TITLE
Shell Command Injection : switch-c.tool.in

### ISSUE THREAD

**Issue by TheRegRunner** [mate-desktop/pluma#171]
os.system("pluma %s.h" % ".".join(name.split('.')[:-1]))

In the line above, a shell command like 
;xeyes;
in the "PLUMA_CURRENT_DOCUMENT_NAME" may be executed by a shell.
Should not use os.system, use subprocess please.

**Comment by monsta** [comment]
Ok, https://github.com/mate-desktop/pluma/commit/4d84579eace005ab4ab07646bc693da22c75bfc4 should fix it, please test.

**Comment by TheRegRunner** [comment]
[script.txt](https://github.com/mate-desktop/pluma/files/133246/script.txt)

test my fix please

**Comment by monsta** [comment]
Works fine. Pushed in https://github.com/mate-desktop/pluma/commit/68665ebb450fb95e05e2b89b0477b8ebcb4977b2.
