### ISSUE TITLE
Adoc files not shown in file browser panel

### ISSUE THREAD

**Issue by foss-scribe** [mate-desktop/pluma#174]
Pluma does not display asciidoc (*.adoc) files in in file browser planel. I'm guessing this is because there's no mime type for this type of file. However when I create a new mimi type in Ubuntu Mate (15.10) the problem persists

**Comment by foss-scribe** [comment]
Update: by creating a user-level mime with these instructions:

http://askubuntu.com/questions/478029/adding-mimetypes-in-ubuntu-14-04

I was able to get adoc files to be displayed in Pluma.

Given that it didn't work at the system level, I'll chalk this up as an Ubuntu issue rather than a Pluma issue and mark this issue as closed.

**Comment by flexiondotorg** [comment]
@foss-scribe, please share details of what you did so I can update the defaults in Debian and Ubuntu MATE.

**Comment by foss-scribe** [comment]
@flexiondotorg, I actually documented it in a roundabout way earlier this arvo over at the community site: https://ubuntu-mate.community/t/creating-new-mime-types/4351

I had to take screen shots though of my code since I could put XML in the discourse post. I did the change on my work machine, and I can post the code here my time tomorrow morning if that's okay 

Cheers,
Chris

**Comment by foss-scribe** [comment]
~/.local/share/mime/text/x-adoc.xml

```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="text/x-adoc">
  <comment>AsciiDoc document</comment>
  <glob pattern="*.adoc"/>
</mime-type>
```

~/.local/share/mime/packages/x-adoc.xml

```
<?xml version="1.0" encoding="utf-8"?>
<mime-type xmlns="http://www.freedesktop.org/standards/shared-mime-info" type="text/x-adoc">
  <comment>AsciiDoc document</comment>
  <glob pattern="*.adoc"/>
</mime-type>
```
