### ISSUE TITLE
Syntax highlighting for CSS

### ISSUE THREAD

**Issue by MahzunGozler** [mate-desktop/pluma#182]
Syntax highlighting doesn't work for the property "border-radius" in a CSS style sheet, the property remains white.
Thank you
![border-radius](https://cloud.githubusercontent.com/assets/18640683/14766439/1fbef2ce-0a0a-11e6-8214-6d1ea4bf2a21.png)

**Comment by raveit65** [comment]
Hmm, works here with all color schemes
![pluma](https://cloud.githubusercontent.com/assets/961604/14767541/57a16096-0a28-11e6-8f0b-5db582e4059e.png)

**Comment by cranes-bill** [comment]
It depends of **gtksourceview**.
I guess that @MahzunGozler uses `gtksourceview-2` and @raveit65 uses `gtksourceview-3`...

**Comment by raveit65** [comment]
Confirmed with pluma gtk2 build, but than it looks like an bug in gtksourceview-2.

**Comment by raveit65** [comment]
@MahzunGozler 
Can you please file out a report against gtksourceview-2 to see what their devs say?

This should be reproducible with another gtk2 text-editor.

**Comment by raveit65** [comment]
Ok, i see the same issue with 'juffed' which is also gtk2 based.

**Comment by cranes-bill** [comment]
@MahzunGozler, I added some extra words to the file.
Here is the workaround for you, just copy and paste the following on the terminal:
```
mkdir -p ~/.local/share/gtksourceview-2.0/language-specs
wget https://gist.githubusercontent.com/cranes-bill/9d76313de3b1e39ee19e7749a13c4dfe/raw/4a9f7553ee03e93e1c560a511124abda4f1abd4c/css.lang -O ~/.local/share/gtksourceview-2.0/language-specs/css.lang

```
The diff between `/usr/share/gtksourceview-2.0/language-specs/css.lang` and `~/.local/share/gtksourceview-2.0/language-specs/css.lang` will show you what is added.

**Comment by raveit65** [comment]
Thank you, works great.
Because it is not a issue with pluma i will close the report.
.....blame me if you don't agree ;)

**Comment by MahzunGozler** [comment]
@cranes-bill, @raveit65 Thank you a lot :) ! It works great ! No problem @raveit65  ;) thanks

**Comment by monsta** [comment]
Unfortunately, GTK+2 version of gtksourceview isn't maintained upstream. So until we switch Pluma to GTK+3 only, you'll have to apply patches like the one posted above...
