### ISSUE TITLE
the warning window closing unsaved multiple tabs is too big

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#186]
![unsavedchanges](https://cloud.githubusercontent.com/assets/7734191/16542799/834e0214-40b8-11e6-9515-c30170b850bb.png)

I suggest two lines:

**There are 2 documents with unsaved changes.
Save changes before closing?**
##

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/pluma/commit/f04342f59f722635bb8178a3816f07b54a7319f9 in a bit different way. IIRC we have the same fix in mate-polkit and maybe somewhere else...

**Comment by monsta** [comment]
Oops, wrong button. I didn't mean to reopen it.
