### ISSUE TITLE
Unsupport for zh_CN in windows coding

### ISSUE THREAD

**Issue by feiying** [mate-desktop/pluma#187]
Copy the file which create and edit in windows7 to fedora system,  open the file via pluma text editor, then the content display confusion, please help to deel with it. Thanks !!!

platform: Intel x86_64
os: fedora mate 21
pluma version: pluma-1.8.1-2.fc21.src.rpm

**Comment by cranes-bill** [comment]
Use **enca** or **iconv** to convert the file in your system _LOCALE_!

**Comment by monsta** [comment]
GitHub isn't a support forum. Besides, version 1.8 is too old, we don't support it these days.
