### ISSUE TITLE
[Spell Checker plugin] "Always autocheck" doesn't apply to new documents

### ISSUE THREAD

**Issue by iwojia** [mate-desktop/pluma#188]
Since issue https://github.com/mate-desktop/pluma/issues/90 and PR https://github.com/mate-desktop/pluma/pull/146, the Spell Checker plugin has had a configuration option to "Always autocheck" -- this works when opening any existing document, but does not work when creating a new document....

**Comment by monsta** [comment]
@sleeveroller: can you please take a look at this issue?

**Comment by monsta** [comment]
Fixed in https://github.com/mate-desktop/pluma/commit/e9b5711bc16331ee7de21573f82999053131a9ff.
