### ISSUE TITLE
Change the name of the icon=accessories-text-editor to icon=pluma

### ISSUE THREAD

**Issue by erikdubois** [mate-desktop/pluma#192]
In data/pluma.desktop.in.in you are declaring the icon name for pluma
When making the sardi icons 'more' perfect, I had just changed this icon
accessories-text-editor because it is used in one of the icons in evolution (mail client).

May I suggest you use a more direct naming like "pluma"?
I will be using this icon name in the sardi icon set.

Working on arch and mate now.

content of desktop file

[Desktop Entry]
_Name=Pluma
_GenericName=Text Editor
_Comment=Edit text files
Exec=pluma %U
Terminal=false
Type=Application
StartupNotify=true
MimeType=text/plain;
**Icon=accessories-text-editor**
Categories=GTK;Utility;TextEditor;
Keywords=text;editor;MATE;tabs;highlighting;code;multiple;files;pluggable;
X-MATE-DocPath=pluma/pluma.xml
_X-MATE-FullName=Pluma Text Editor
X-MATE-Bugzilla-Bugzilla=MATE
X-MATE-Bugzilla-Product=Pluma
X-MATE-Bugzilla-Component=general
X-MATE-Bugzilla-Version=@VERSION@
X-MATE-Bugzilla-ExtraInfoScript=@FULL_LIBEXECDIR@/pluma/pluma-bugreport.sh
##

**Comment by monsta** [comment]
Which icon themes have the "pluma" icon?

**Comment by monsta** [comment]
@raveit65: I think we can close this since there's no icon named "pluma" in any icon theme - unless I missed something.
