### ISSUE TITLE
slow searching due to animation

### ISSUE THREAD

**Issue by roderickmackenzie** [mate-desktop/pluma#196]
Hi,
  I've been using pluma every day to write C/python  for the last 2+ years , and up until I've really liked it.  I jumped from gedit to pluma as I could not deal with the new gedit interface.  I've just upgraded from fedora 23 to 24 and started using pluma again.  I've noticed that when I hit crtl+F to do find, the search window pops up just fine.  I type in what I want to find, then hit return.  There is then a noticeable delay (0.2-0.5) seconds between be hitting return and the find dialog closing.  The main text editor window then animates scrolling to the first found item.  The delay in closing the dialog box followed by the time for animated scrolling of the window to the first found item, adds up to a noticeable and pretty irritating delay.  It would be good if the scrolling animation could be turned off and the delay in closing the find dialog removed.  I've temporally switched to kate, but it's not as good as old pluma.  On another note, I also find it difficult to differentiate between tabs as there is no separation between them - although this could be a gtk3/fedora issue.
best,
Rod
##

**Comment by raveit65** [comment]
First,first i switched pluma to gtk3 for f24.
>  I've noticed that when I hit crtl+F to do find, the search window pops up just fine. I type in what I want to find, then hit return. There is then a noticeable delay (0.2-0.5) seconds between be hitting return and the find dialog closing.

Do you mean that window?
![bildschirmfoto zu 2016-08-10 16-52-46](https://cloud.githubusercontent.com/assets/961604/17558468/008b414e-5f1b-11e6-850f-b8f0ce29e7cc.png)
This window does not close if you hit return, it stays always open until you close it with the close button. And i don't see a delay here, but maybe this depends on the document size.
And what do you mean with animated scrolling?

> On another note, I also find it difficult to differentiate between tabs as there is no separation between them - although this could be a gtk3/fedora issue.

This depends on the theme and how notebook tabs are styled.
I guess you mean not the active tab. With most mate themes the inactive tabs get a highlight if you move over with mouse on the tab.
Which theme are you using?

**Comment by raveit65** [comment]
Hmm, you are using Adwaita theme, are you using gnome-shell?
Here in f24 with Mate and a mate theme i can't really reproduce such a delay.
And the tab styling is from adwaita theme.

**Comment by lsh-0** [comment]
+1

this is the first result for "disable find animation in pluma"

mate has just made the jump to pure gtk3 and I just can't stand it. Thankyou for all your work. I think after many many years (10+?) of using gedit/pluma it's time to jump ship.

**Comment by roderickmackenzie** [comment]
Hi All,  Just came back to this thread after getting a notification about lsh-0's post.  Thanks for your work, but I do have to say that also I've moved to kwrite because of this, which was a bit of a shame.  Especially, as initially pluma was a haven for me, from the way gedit went with the move to gtk3.  I have found kwrite a bit clunky to use though as it does not have tabs.

As someone who has just moved an application from gtk2.x to qt 5, I have to say I really don't like the way gtk3 is going.  Especially on it's poor cross platform support (think OpenGL widgets)

**Comment by lsh-0** [comment]
hey man - I switched to kwrite (and probably kde) this morning after posting that :) 
pluma wasn't the sole cause, it was just the last straw. meld, caja, the file picker, the slowness of development, lack of features, the seeming deliberate deafness to users in the gtk3/gnome3/unity camp - and now stupid scrolling animations I can't turn off when in pluma. 

kwrite looks really promising (and sophisticated). no tabs will take a little getting used to.

**Comment by raveit65** [comment]
Guys, what you said isn't wrong.
The animation is part of gtk+-3 itself. We can't do anything to disable it.

**Comment by roderickmackenzie** [comment]
For anybody who is interested this is my thoughts/experiences on moving from gtk to qt: https://www.youtube.com/watch?v=OQ50sjC_udY&t=8s

**Comment by aj-mcl** [comment]
Sorry for the thread necromancy - but having encountered this myself, I wanted to let you know that this animation can be disabled in dconf-editor. I don't recall the exact setting - I found it last night after searching through every setting that could disable animations everywhere, and I'm typing this on a work PC without MATE - but it did make Pluma usable again on my Ubuntu MATE 18.04 install.

If/when I isolate the setting in question, I'll post again.

(It was a great relief finding it - I would have had to downgrade to 16.04 otherwise!)

**Comment by aj-mcl** [comment]
The setting is /org/mate/desktop/interface/gtk-enable-animations

**Comment by lsh-0** [comment]
```bash
$ gsettings get org.mate.interface gtk-enable-animations
true
$ gsettings set org.mate.interface gtk-enable-animations false
$ gsettings get org.mate.interface gtk-enable-animations
false
```

This appears to also set the value at `org/mate/desktop/interface/gtk-enable-animations` when viewed through `dconf-editor`.
