### ISSUE TITLE
Pluma clears recent documents when opened as su from terminal

### ISSUE THREAD

**Issue by colibris79** [mate-desktop/pluma#198]
Hi,
I am using Mint 17.3 Mate and these have been happening for a while. Whenever I open Pluma as superuser from terminal or open a document with Pluma from terminal, I edit and I save it. My recent documents list are gone (from pluma, mint menu and other apps as well). For example:

sudo pluma 
Or
sudo pluma

After editing and saving, they're gone.

If I open with gksudo is not happening. Is this expected to be like this?
##

**Comment by sc0w** [comment]
Do you have same problem with latest version?

**Comment by colibris79** [comment]
Hi,
I am on Mint 18.3 now and using gksudo xed it works fine

**Comment by colibris79** [comment]
Mint 18 doesn't use pluma anymore, it uses xed as default text editor. Anyways launching pluma with gksudo solved the problem (this issue was 2 years old and was for Mint 17.3)
