### ISSUE TITLE
How to - use command line to open file using existing instance?

### ISSUE THREAD

**Issue by markd89** [mate-desktop/pluma#200]
Suppose I have an instance of Pluma already running with some files being edited.

From the shell, I run: 

pluma "/home/mark/Documents/backup notes.txt"

This opens a new instance of Pluma rather than opening the file in a new tab in the instance that is already running. Is there a clever way to make Pluma use the existing instance?

Thanks!
Mark

**Comment by raveit65** [comment]
weird, this is working well here.
'pluma foo' opens a terminal and the command stays open.
'pluma bar' opens the document bar as a new tab in existing pluma instance.

Sorry, i will close this report as you didn't post needed information like mate version, pluma version and distro.
Too many users are thinking they are the only one who use MATE ;)
....i will re-open it if i see the infos here.

**Comment by markd89** [comment]
I seem to be able to duplicate it by...

1. Pluma is not running.
2. Using Nautilus, I click on a file so that Pluma opens it.
3. Using a Terminal session open another file i.e. pluma "/home/mark/Documents/backup notes.txt"

Result is a second instance of Pluma.

Note: If both files are opened from the command line before Pluma is running then it works properly (as in your test).

I am using Pluma 1.8.1 under Debian Jessie. Yes, I know this is older but would appreciate if you could retest using my steps above.

Thanks much & am a Pluma fan!
Mark

**Comment by raveit65** [comment]
> I am using Pluma 1.8.1 under Debian Jessie. Yes, I know this is older but would appreciate if you could retest using my steps above.

Sorry, i can't. I'm using fedora/centos which don't use obsolete versions.
....job for other guys.

**Comment by raveit65** [comment]
> Using Nautilus, I click on a file so that Pluma opens it.
Are you using gnome?  :smile:

**Comment by markd89** [comment]
Yes, I confess I am.

**Comment by raveit65** [comment]
With a fedora 23 VM and Mate-1.14 inside gnome-shell.
1. openning 'foo' with pluma from nautilus.
2. 'pluma bar' in mate-terminal opens the document 'bar' as a new tab in existing pluma instance.

Sorry, since 2 years i don't have any fedora/centos installation with MATE-1.8.x anymore :smile: 
........debian is always pretty much obsolete ;)

**Comment by monsta** [comment]
We don't support 1.8.x these days. I know it would be nice for Debian Jessie users, but our team is quite small.
