### ISSUE TITLE
--new-document option stopped working from keybinding

### ISSUE THREAD

**Issue by gommoichao** [mate-desktop/pluma#203]
how it's supposed to work:
if a pluma window is already open (with anything other than a new, unedited document) and I hit my keybinding for pluma (`<Control><Alt>p`), it should open a new tab in the existing window

what's happening instead:
a new pluma window is opened. if i hit my keybinding again, however, it will open a new tab within the window the first keybinding press opened.

this worked correctly in pluma 1.12.1 in Fedora 22
this no longer works in Fedora 23 or 24, even with a lower version of pluma (e.g. 1.10.2 in F23).

it seems this issue is a side-effect of an update to another piece of software between Fedora 22 and Fedora 23 -- any ideas?

You can use the following commands to set the keybinding (this will overwrite if you already have a custom keybinding in this position).
```
gsettings set org.mate.Marco.global-keybindings run-command-1 '<Control><Alt>p';
gsettings set org.mate.Marco.keybinding-commands command-1 'pluma --new-document';
```

**Comment by sc0w** [comment]
I think it was already fixed

@gommoichao do you have same problem with latest version?

**Comment by gommoichao** [comment]
confirmed, no longer occurring for me in pluma 1.20.2 on fedora 28
