### ISSUE TITLE
Search results ignores layout choice for folder

### ISSUE THREAD

**Issue by politas** [mate-desktop/pluma#204]
I have my default folder view set to icon view. There is one folder that I use list view in, and I regularly need to search in it (it contains files with hash codes prepended for programmatic searching).

Every time I enter search details, pluma resets to icon view. I really need to see the date modified on these results, so I have to change the view every time.

Search results should use the same view choice as the folder being searched.

**Comment by monsta** [comment]
How is it related to Pluma?

**Comment by politas** [comment]
Ah, it's not. Wrong program. Sorry

**Comment by politas** [comment]
Re-logged under caja, where it belongs.
