### ISSUE TITLE
Pluma 1.17.1 fails to build

### ISSUE THREAD

**Issue by omega13a** [mate-desktop/pluma#207]
I'm trying to make an RPM for Pluma 1.17.1 ( had no problems making one for Pluma 1.17.0). It doesn't mater if I am using the compiling it with ligcc or just plane gcc. It fails at the same place.

Attached is the spec file I'm using as well as the output I get when I try to build.

[pluma.txt](https://github.com/mate-desktop/pluma/files/644963/pluma.txt)
[pluma build output.txt](https://github.com/mate-desktop/pluma/files/644966/pluma.build.output.txt)

If it helps, I was building it on Fedora 24.

**Comment by willysr** [comment]
I had this problem as well while building in VM (init 3) but it works in my desktop (which is running in X).

**Comment by monsta** [comment]
Thanks for spotting it - https://github.com/mate-desktop/pluma/commit/0c051115caa2f9bb0f3598a0cd2cf47a97ec1a09 should take care of it.

**Comment by monsta** [comment]
Version 1.17.2 is released with the fix.
