### ISSUE TITLE
Need help adding feature to xed from pluma

### ISSUE THREAD

**Issue by calexil** [mate-desktop/pluma#209]
What part of the pluma code allows for the mouse wheel to scroll through open document tabs?

that feature is strangely missing in xed and I wanna ad it back in

**Comment by monsta** [comment]
Actually, it doesn't work in GTK+3 build of Pluma.

**Comment by JosephMcc** [comment]
This is now working in xed and can probably be easily ported to pluma: https://github.com/linuxmint/xed/commit/50c216b17bb56573613de0f0e588687713f8c3f7
