### ISSUE TITLE
the tab closes unexpectedly with middle click under the line numbers

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#215]
pluma 1.16.0

with middle click on the red area, the tab will close:

![pumacloses](https://cloud.githubusercontent.com/assets/7734191/23591021/32f66d80-01ea-11e7-95d9-a04bc867dd79.png)

Implement middle-click tab closing: https://github.com/mate-desktop/pluma/commit/9d1bf65037d56ced8c3d4396902e83e286222914

**Comment by sc0w** [comment]
more info: with a lot of tabs, if I do middle click in that area in a tab, pluma always try to close the first tab

**Comment by monsta** [comment]
This is also reproducible in GTK+2 build of 1.16, so I picked the fix to 1.16 branch.
