### ISSUE TITLE
pluma closes tab unexpectedly with middle click while the left click is holding pressed

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#228]
how to reproduce:

in the red area:

![image4493](https://cloud.githubusercontent.com/assets/7734191/26037443/ce61d162-38f2-11e7-9616-8cc59ac650ce.png)

1. holding pressed left click

2. middle click while the left click is pressed

video:

[issuemiddleclick.zip](https://github.com/mate-desktop/pluma/files/999696/issuemiddleclick.zip)

confirmed in pluma 1.16.1 and 1.18.0

**Comment by raveit65** [comment]
weird, after the action in the video,  i noticed that  the cursor change to 'hand' if you open a new document with toolbar button.

**Comment by sc0w** [comment]
@raveit65 yes, my fix solves it too
