### ISSUE TITLE
Please add an option to disable the tabs when the sidebar is used

### ISSUE THREAD

**Issue by malheum** [mate-desktop/pluma#23]
Hello,

I am usually using the sidebar, for myself the sidebar (enabled by pressing F9 or through the menubar) is much more usable than those tabs.

However, I have not found a way to disable those now redundant tabs which the editor shows. Those tabs now just take up space on my screen that I'd rather use for showing my files. Plus it is redundant, and I do hate redundant stuff on my screen.

Could you please add an option under the menubar like ->view->disable tabs ?

Thanks
BR Max.

![bildschirmfoto-unsaved document 6 - pluma](https://f.cloud.github.com/assets/4420848/497904/e492400a-bc07-11e2-909b-eae343622aaf.png)
##

**Comment by h1aji** [comment]
Hi, is there an option to disable tabs completely?
Would be nice to have.

**Comment by adamltaylor** [comment]
+1
