### ISSUE TITLE
Recent Documents gone missing

### ISSUE THREAD

**Issue by texstar** [mate-desktop/pluma#232]
Pluma 1.18.2 does not repopulate recent documents anymore.

**Comment by raveit65** [comment]
Not here!

**Comment by texstar** [comment]
When I click the down triangle next to Open it says "No items found".

**Comment by sc0w** [comment]
@texstar some warning running pluma with a terminal ?

**Comment by texstar** [comment]
Just a theme warning the Black Mate theme. (pluma:18384): Gtk-WARNING **: Theme parsing error: <data>:5:22: The :focused pseudo-class is deprecated. Use :focus instead.

How to duplicate. 
Delete .local/share/recently-used.xbel file
Start Pluma and open some text files
Close Pluma. 
recently-used.xbel is now populated with recent text files you opened
Open Pluma nothing is listed as being recently opened.

Works in 1.8.0. Does not work in 1.8.2.

**Comment by sc0w** [comment]
It works fine here with 1.18.2

**Comment by texstar** [comment]
I know it can be frustrating when you cannot duplicate an issue. I will simply apply a revert patch to fix it for us.

https://pastebin.com/zbhnkkLD

Thanks for responding.

**Comment by monsta** [comment]
That patch doesn't look related to recent documents.

**Comment by sc0w** [comment]
I think it was already fixed in the past, @texstar you experience the same issue with 1.18.5 or 1.20.2 ?

**Comment by texstar** [comment]
IT has been fixed. Thank you very much.
