### ISSUE TITLE
pluma closes tab unexpectedly with middle click while the right click is holding pressed

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#256]
how to reproduce:

in the red area:

![image4493](https://cloud.githubusercontent.com/assets/7734191/26037443/ce61d162-38f2-11e7-9616-8cc59ac650ce.png)

It needs to do **quickly** to reproduce:

1. holding pressed right click

2. middle click while the right click is pressed

3. release the buttons

(pluma 1.18.2 and git master)

**Comment by raveit65** [comment]
Ok, after i found out to right-click in headers of the notebook i could reproduce the issue.

**Comment by monsta** [comment]
I have a feeling I already saw such a report, and it was fixed... O_o

**Comment by raveit65** [comment]
Your feeling is OK :-)
https://github.com/mate-desktop/pluma/pull/229
But the new PR is for right-clich in notebook header.
Old one was about right-click in document itself.

**Comment by sc0w** [comment]
@monsta 

the "middle click implementation" to close tabs give us in the past some issues:

https://github.com/mate-desktop/pluma/issues/250 https://github.com/mate-desktop/pluma/issues/228 and https://github.com/mate-desktop/pluma/issues/215

and I hope this is the fourth and last issue

at this time, to reproduce, it needs to do **quickly** holding down [right+middle] click (in this order)

@raveit65 I can reproduce it in the document too, in the red area I described in the first comment

**Comment by raveit65** [comment]
> the "middle click implementation" to close tabs give us in the past some issues:
> #250 #228 and #215
> and I hope this is the fourth and last issue

@sc0w 
But in which branch or git history is the culprit commit?
Btw. Do we need all fourth new commits for a new 1.18 point release?
Or does the issue only exist in master?

**Comment by sc0w** [comment]
@raveit65 I can confirm, the commit https://github.com/mate-desktop/pluma/commit/9d1bf65037d56ced8c3d4396902e83e286222914 makes the issues https://github.com/mate-desktop/pluma/issues/228 https://github.com/mate-desktop/pluma/issues/215 and this issue https://github.com/mate-desktop/pluma/issues/256

The issue https://github.com/mate-desktop/pluma/issues/250 is not related to the middle click implementation

> Do we need all fourth new commits for a new 1.18 point release?

Three commits, the issue https://github.com/mate-desktop/pluma/issues/215 was already fixed in 1.18 branch

In pluma 1.18.2 I can reproduce the issues https://github.com/mate-desktop/pluma/issues/228 https://github.com/mate-desktop/pluma/issues/250 and this issue https://github.com/mate-desktop/pluma/issues/256
