### ISSUE TITLE
new pluma document doesn't show in the same window if it exists in the same workspace

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#261]
#### Expected behaviour

open new pluma document in the same window if it exists in the same workspace

#### Actual behaviour

it doesn't open in the same window

#### Steps to reproduce the behaviour

the easy way:

- open an existing file using terminal with (caja-open-terminal) **right click on folder -> open in terminal**  ( $ pluma filename )

- go in panel to `applications -> accesories -> pluma`

it open new pluma window instead the previous window

this is wrong, but it is very wrong the behavior of notebook in the new window:

go to the window with the "unsaved document" and see the behavior of mouse over the tab:

right click: it doesn't show the popup menu

make new tab in that window, and try to move it with the mouse: it doesn't work

all is wrong

#### MATE general version

1.18.0

#### Package version

it happens with pluma 1.18.2 and 1.8.1 (yes, very old version) with gtk3 (gtk 3.22.24), with 1.8.1 in gtk2 it works as expected

#### Linux Distribution

debian buster/testing

**Comment by raveit65** [comment]
Hmm, i followed your steps to reproduce but here pluma opening from menu gives me always a new tab in existing pluma window.
I am using pluma from master here.

**Comment by raveit65** [comment]
Same with opening pluma from terminal.
https://www.dropbox.com/s/s60jtl0btcat1yk/pluma.ogv?dl=0

**Comment by sc0w** [comment]
@raveit65 I edit my first comment, try again, but open with terminal the first file: $ pluma filename

**Comment by raveit65** [comment]
I did open the fist window from terminal and second from menu.
The result is the same . I have one pluma window with 2 tabs.

**Comment by raveit65** [comment]
Same with 1.18.3
[rave@f26 ~]$ rpm -qa pluma
pluma-1.18.3-1.fc26.x86_64

**Comment by sc0w** [comment]
see the video:

[out-51.ogv.zip](https://github.com/mate-desktop/pluma/files/1489335/out-51.ogv.zip)

weird, debian issue?

I can reproduce it too in debian stable/stretch vm with pluma 1.16.1

@lukefromdc @monsta can you reproduce this issue?

**Comment by raveit65** [comment]
I did the same steps like your in this video. i can't reproduce it.
https://www.dropbox.com/s/f3f6rn43mw3s7ow/pluma-2.ogv?dl=0

**Comment by sc0w** [comment]
more info: I can't reproduce the issue if I run terminal in panel with the launcher

the problem is with **right click on folder -> open in terminal** (caja-open-terminal)

an later, the steps...

**Comment by raveit65** [comment]
same result with:
1. open a folder in terminal from caja context-menu
2. open an document from the terminal with 'pluma file'
3. open an new pluma instance from panel launcher or menu
New pluma document opens in same pluma window.

**Comment by raveit65** [comment]
Ok, don't know if this is a good message.
I can reproduce the issue with ubuntu-17.10 VM with pluma-1.18.2 from repos and pluma compiled from master.
I will test it with rhel7 now.
At least i have found a distro where i can test the fix.

**Comment by raveit65** [comment]
And i can reproduce the issue in centos-7.4 with Mate-1.18 (gtk3) and pluma-1.18.3.
Note, pluma-1.18.3 here is build from same SPEC file as i use for fedora builds.
So, it look likes that the issue is caused by another package which is used in the background.
Or in other words, what is in fedora better than in other distros........... ;-)

**Comment by raveit65** [comment]
Maybe it depends on  gtk3 version as PR is about GtkScreen?
centos7.4:
[rave@localhost ~]$ rpm -qa gtk3
gtk3-3.22.10-4.el7.x86_64

fedora 26:
[rave@mother ~]$ rpm -qa gtk3
gtk3-3.22.21-2.fc26.x86_64

**Comment by lukefromdc** [comment]
Confirmed here, though this is something I have often deliberately made use of it is not a consistant behavior. About to test the PR. Since we can drag a tab off the pluma window or use the dcouments>move to new window methods to consistantly open a new window, the PR does not remove a feature unless these  break, will be testing for that.

**Comment by sc0w** [comment]
I can't reproduce the issue with the live https://spins.fedoraproject.org/mate-compiz/

It seems to have all mate components with 1.19

The issue here is in mate 1.18 (with all pluma gtk3 versions)

@raveit65 you can't reproduce the issue with mate 1.18 in fedora?

**Comment by raveit65** [comment]
> It seems to have all mate components with 1.19

> The issue here is in mate 1.18 (with all pluma gtk3 versions)

> you can't reproduce the issue with mate 1.18 in fedora?

Yes, it doesn't matter if i use 1.18 or 1.19 in fedora.
Btw. the fixed commit doesn't apply on 1.18 branch
So, i used 1.19 for testing the commit in rhel7/centos7
It look like it is complete independent if i use 1.19 or 1.18, i can't reproduce it in fedora, only in rhel/centos or ubuntu-17.10.
Btw. here is the MATE-Compiz live iso for f26 with Mate-1.18
https://kojipkgs.fedoraproject.org/compose/26/latest-Fedora-26/compose/Spins/x86_64/iso/

**Comment by monsta** [comment]
I'm pretty sure I've seen Pluma opening a new window when opened via different methods (menu, terminal...) - but now I tried to reproduce, and it doesn't happen. Debian Stretch + all MATE from git master.

**Comment by monsta** [comment]
Mint 18.3, MATE 1.18 with all our latest 1.18.x packages. Not reproducible as well...

**Comment by raveit65** [comment]
As GtkScreen is part of gtk we should compare gtk+ versions.

centos7.4:  (reproducible)
gtk3-3.22.10-4.el7.x86_64

fedora 26: (unreproducible)
gtk3-3.22.21-2.fc26.x86_64

fedora 27: (unreproducible)
gtk3-3.22.26-1.fc27.x86_64

**Comment by sc0w** [comment]
@monsta you tried the first window with terminal launched from caja?, and the second window with click in launcher, or double click on file in caja.

![openterminal](https://user-images.githubusercontent.com/7734191/33154175-cbb6bde8-cfe6-11e7-9129-7efc29360945.png)

I can reproduce it in debian stable/stretch(vm) and testing/buster

**Comment by monsta** [comment]
Nope, I always used a terminal either opened from mintMenu or restored from saved session.
Ok, opening terminal from Caja somehow helps to reproduce it. Only in Ubuntu 17.10 though... don't know why.
