### ISSUE TITLE
[Feature Request] Allow scrolling on notebook tabs to change the active page

### ISSUE THREAD

**Issue by Lbif-RU** [mate-desktop/pluma#271]
In Linux Mint in Xed has been added "Allow scrolling on notebook tabs to change the active page", but this does not work in Fedora 27. Can you add a similar functionality to Pluma?
![xed](https://user-images.githubusercontent.com/35063022/34649825-3880aab2-f402-11e7-8138-62ba45815308.png)

**Comment by sc0w** [comment]
we have that feature in mate-terminal with horizontal/vertical scroll

**Comment by sc0w** [comment]
Done in https://github.com/mate-desktop/pluma/pull/276
