### ISSUE TITLE
please install .appdata.xml to correct metainfo location

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/pluma#280]
In Debian, the .appdata.xml (apspstream) file goes into /usr/share/metainfo.

See here for the workaround, I currently have in debian/rules:
https://anonscm.debian.org/cgit/pkg-mate/pluma.git/commit/?id=7ed77a9089d89817125abddce69afc2f10c40f2b

**Comment by monsta** [comment]
Thanks, committed in https://github.com/mate-desktop/pluma/commit/eb0cc59066bb397475adf9105741ea9d45bdb678.
