### ISSUE TITLE
pluma crash when trying to open file with BOM at begining

### ISSUE THREAD

**Issue by hkalina** [mate-desktop/pluma#301]
#### Expected behaviour
File with BOM should be opened correctly.

#### Actual behaviour
pluma crash:
Program terminated with signal SIGABRT, Aborted.
#0  _nl_load_domain (domain_file=<optimized out>, domainbinding=<optimized out>) at loadmsgcat.c:1055
1055			    domain->malloced = mem;
[Current thread is 1 (LWP 16478)]
(see downstream report for full stacktrace)

#### Steps to reproduce the behaviour
Try to open attached file test.php using pluma: [test.php.zip](https://github.com/mate-desktop/pluma/files/1841426/test.php.zip)
(note: the problem occure only when file has *.php extension, it is opened correctly when I rename it to *.txt - maybe it is related to syntax highlight)

#### MATE general version
mate-desktop.x86_64   1.19.3-1.fc27

#### Package version
pluma.x86_64    1.19.3-1.fc27

#### Linux Distribution
Fedora 27

#### Link to downstream report of your Distribution
https://bugzilla.redhat.com/show_bug.cgi?id=1558487 (retrace included)

**Comment by sc0w** [comment]
The crash is caused in `pluma-document.c` by the line `gtk_source_buffer_set_language`

**Comment by rcaridade145** [comment]
> the problem occure only when file has *.php extension

Searching a bit on google it seems the recommended fix is to either remove it or ignore it when it is php

[https://stackoverflow.com/questions/3255993/how-do-i-remove-%C3%AF-from-the-beginning-of-a-file](url)

**Comment by sc0w** [comment]
@monsta I don't know.

In https://github.com/mate-desktop/pluma/pull/357 I disabled `gtk_source_buffer_set_language` if the file is `php` with `bom`.

**Comment by monsta** [comment]
I see, it's a workaround, and the actual problem is probably upstream. If we'd find the upstream report, we could mention it in the comments.
