### ISSUE TITLE
Find+replace with capture groups

### ISSUE THREAD

**Issue by funny-falcon** [mate-desktop/pluma#310]
#### Expected behaviour
Ability to replace with capture groups:
```
find: (ab)(cd)
replace: \1zx\2
```
should replace `abcd` with `abzxcd`

#### Actual behaviour
it is replaced with `\1zx\2'

#### Package version
Pluma 1.18.2

#### Linux Distribution
Ubuntu MATE 17.10

**Comment by funny-falcon-at-joomcode** [comment]
Oh, sorry, it is duplicate for #254

**Comment by raveit65** [comment]
Ok, why not closing it in this case?
