### ISSUE TITLE
Searching with "Match regular expression" and "Search backwards" only selects one occurrence

### ISSUE THREAD

**Issue by ecm-pushbx** [mate-desktop/pluma#322]
Test file test.txt contains the following:

===
A

A B

B C

A B

B C

A B

B C

A D

D

A D

D

===

Here shown with line numbers, in the pluma window:

![screenshot at 2018-05-22 13-14-23](https://user-images.githubusercontent.com/31538682/40359185-1dadfecc-5dc2-11e8-8f11-351293c91268.png)

#### Expected behaviour

Find with "Match regular expression", "Search backwards", and "Wrap around" all set, should cycle through selecting the occurrences of the search string whenever the "Find" button is pressed. (Lines 3, 7, 11.)

#### Actual behaviour

When the "Find" button is pressed with these options on, the last occurrence of the search string is selected. Repeatedly pressing "Find" only selects the last occurrence over and over again. (Line 11.)

#### Steps to reproduce the behaviour

1. Open test.txt as shown above.

2. Ctrl+F

3. Search for: A B

4. Set options as specified.

5. Press "Find" button repeatedly.

#### MATE general version

1.20.1-2

#### Package version

1.21.0, compiled from source of revision git 7b7cd3f48b52+

#### Linux Distribution

Debian buster

**Comment by ecm-pushbx** [comment]
I just figured out that it isn't always the last occurrence that is selected. Searching for " [^C]" (without "Search backwards") cycles through selecting the match on line 3, 7, 11, 15, 19. The same search string with "Search backwards" on always selects the match in line 11.

**Comment by sc0w** [comment]
I will put here my annotations:

we have in the function `pluma_document_search_backward` in `pluma-document.c`:

https://github.com/mate-desktop/pluma/blob/master/pluma/pluma-document.c#L2060

```
		if(!PLUMA_SEARCH_IS_MATCH_REGEX(doc->priv->search_flags))
		{
			found = gtk_text_iter_backward_search (&iter,
							       doc->priv->search_text,
							       search_flags,
							       &m_start,
							       &m_end,
							       start);
		}
		else
		{
			found = pluma_gtk_text_iter_regex_search (&iter,
								  doc->priv->search_text,
								  search_flags,
								  &m_start,
								  &m_end,
								  end,
								  FALSE,
								  &doc->priv->last_replace_text);
		}

```

and the function `pluma_gtk_text_iter_regex_search` is on `pluma-utils.c`:

https://github.com/mate-desktop/pluma/blob/master/pluma/pluma-utils.c#L1558

(with a lot of weird indentations)

**Comment by ecm-pushbx** [comment]
Correction: The bug with that patch is now less apparent, but it still fails somewhat. "A B" regexp backwards selects lines 11 then 7 then 3. But " [^C]" selects the same lines (11 then 7 then 3), but should also select 19 and 15.

**Comment by sc0w** [comment]
yes, I just found that fix too :)

I opened https://github.com/mate-desktop/pluma/pull/362

If merged, you can open new issue, the regex doesn't work propertly with backwards

For example, the expression: "A [BD]"

The forward and backwards are different

**Comment by sc0w** [comment]
more info:

with https://github.com/mate-desktop/pluma/pull/362 , the pattern "[A-Z]+" and "match regular expresion" + "search backards"

Pluma only found the first occurence of the pattern at the begining of file, in backwards in all the file.

For example, with test file mentioned in this issue, A is finded, and if that is changed to B (the first item) B will be finded.

"[A-Z]+" can tested with some files to better understood the issue with fordward and backward.

Seems this must fixed in `pluma-utils.c` in the function `pluma_gtk_text_iter_regex_search`

https://github.com/mate-desktop/pluma/blob/master/pluma/pluma-utils.c#L1558

**Comment by sc0w** [comment]
@ecm-pushbx I did some changes, please test again the PR https://github.com/mate-desktop/pluma/pull/362

**Comment by ecm-pushbx** [comment]
Thanks! That fixes the bug as far as I can tell; "A B", " [^C]", "[A-Z]+", and "A [BD]" all seem to work forwards and backwards as they should.
