### ISSUE TITLE
unexpected behavior with dnd selected text

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#329]
pluma 1.20.1

see the video:

[out-62.ogv.zip](https://github.com/mate-desktop/pluma/files/2042193/out-62.ogv.zip)

**Comment by raveit65** [comment]
Since which commit we have all this weirdness with drag&drop ? :)

**Comment by lukefromdc** [comment]
I just did some further tests with this: Yes, it occurs, and neither highlighting the current line nor showing line numbers are necessary to invoke it, only having additional tabs open

**Comment by sc0w** [comment]
@raveit65 old issue, I can reproduce it with pluma 1.14.0 (gtk3)

The previous issue, is an old issue too

**Comment by raveit65** [comment]
Ah, so it was a gtk2-->gtk3 transition issue.
Still wondering that nobody did blame us before :)
