### ISSUE TITLE
new file with double click in forward arrow button (notebook)

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#331]
pluma 1.20.1 (my fault with https://github.com/mate-desktop/pluma/commit/5bed2111c37a1d39eaf7cdad489bd954b5f06227)

double click here, in the forward arrow button in the last tab:

![image823](https://user-images.githubusercontent.com/7734191/40648507-e9b17730-632e-11e8-82b0-b19b4ee22af2.png)

**expected behavior:**

Nothing to do

**actual behavior:**

It opens new empty file

**Comment by raveit65** [comment]
Patch fixes the issue.
