### ISSUE TITLE
new file with double click in the vertical scrollbar

### ISSUE THREAD

**Issue by sc0w** [mate-desktop/pluma#333]
pluma 1.20.1 (my fault with https://github.com/mate-desktop/pluma/commit/5bed2111c37a1d39eaf7cdad489bd954b5f06227)

This is the easy way to reproduce it:

1. click to the right of the last open tab
2. double click in the vertical scrollbar

**expected behavior:**
nothing to do

**actual behavior:**
It opens new empty file

See the video:
[out-64.ogv.zip](https://github.com/mate-desktop/pluma/files/2057765/out-64.ogv.zip)

**Comment by sc0w** [comment]
@vkareh reproducible too, in this case:

1. click in some point of the text in the view
2. double click in the vertical scrollbar

:)

**Comment by lukefromdc** [comment]
I was unable to duplicate this for sopme reason

**Comment by raveit65** [comment]
Confirmed.
