### ISSUE TITLE
[feature request] add configuration for  disable horizontal scrolling over tabs

### ISSUE THREAD

**Issue by zhangn1985** [mate-desktop/pluma#349]
### the issue
when use pluma to open multiple files, horizontal scrolling will help you to switch between files.

but when you use thinkpad's trackpoint, it very easy emits horizontal scrolling while doing vertical scrolling.

it's very bad UX.

so need to add ability to disable horizontal scrolling.

### pluma version, and distro
Debian, 1.20.3

**Comment by sc0w** [comment]
Do you mean the scroll over the notebook tabs?

Currently it works with horizontal and vertical scroll

**Comment by zhangn1985** [comment]
![t](https://user-images.githubusercontent.com/832666/43357581-852e66c6-92b6-11e8-993b-076db7ba7933.PNG)

**Comment by sc0w** [comment]
@zhangn1985 can you test https://github.com/mate-desktop/pluma/pull/354 ?

I don't have that keyboard

**Comment by zhangn1985** [comment]
how can I test it? do you have binary package, or how to compile it?

**Comment by sc0w** [comment]
here are the packages:

[packages_pr.zip](https://github.com/mate-desktop/pluma/files/2292277/packages_pr.zip)

**Comment by zhangn1985** [comment]
@sc0w your package provides pluma 1.21.1, it looks better.

**Comment by zhangn1985** [comment]
@sc0w  https://github.com/mate-desktop/pluma/commit/ed34d929a420da68b49e232a08bc3ca8f980200c 

this commit add horizontal scroll, right?

**Comment by sc0w** [comment]
@zhangn1985 yes, horizontal and vertical scroll. Before that, horizontal and vertical scroll does nothing over the tabs.

Your issue is over the document, or over the tabs?

Over the tabs never worked to scroll the files.

The PR https://github.com/mate-desktop/pluma/pull/354 has no changes in the tabs, only over the document.

**Comment by zhangn1985** [comment]
my issue is horizontal scroll over the tabs.
horizontal scroll will make tabs switch very fast.

horizontal and vertical scroll inside one document, no issue.

**Comment by zhangn1985** [comment]
```
notebook_scroll_event (GtkNotebook    *notebook,
                       GdkEventScroll *event,
                       PlumaWindow    *window)
{
       GSettings *settings;
       settings = g_settings_new ("org.mate.pluma");
	if (event->direction == GDK_SCROLL_UP)
	{
		gtk_notebook_prev_page (notebook);
	}
	else if (event->direction == GDK_SCROLL_DOWN)
	{
		gtk_notebook_next_page (notebook);
	}
	if (g_settings_get_boolean (settings, "h-scroll-tab"))
       {
	if (event->direction == GDK_SCROLL_RIGHT)
	{
		gtk_notebook_prev_page (notebook);
	}
	else if (event->direction == GDK_SCROLL_LEFT)
	{
		gtk_notebook_next_page (notebook);
	}
       }
	return FALSE;
}
```
this is my request.

**Comment by zhangn1985** [comment]
I don't know `scroll_event_cb` and skip some gsetting initial work

**Comment by zhangn1985** [comment]
I find some more detail.
when my mouse is in document window, not in tab bar.

if the document has very long line, horizontal scroll bar shows, and horizontal scrolling will not make tabs switch. even scroll to the end of line, tabs doesn't switch.

but if the document don't have long line, horizontal scrolling will make tabs switch.

**Comment by zhangn1985** [comment]
it looks like a bug!! when document has no long lines, horizontal scroll in document will make scroll over tabs.

**Comment by sc0w** [comment]
@zhangn1985 

not here.

it happens in the packages I attached here? or in the official debian packages?

**Comment by zhangn1985** [comment]
@sc0w it (new findings) happens in official debian packages? I will check my new findings in your packages.

**Comment by zhangn1985** [comment]
@sc0w let me clarify my new findings.

1,
open 2 documents, no long lines, only horizontal scroll in document, expect no scroll over tabs, but actual scroll over tabs. (both official debian packages and your packages)

2,
open 2 documents, with long lines, only horizontal scroll in document, expect horizontal scroll in document, no scroll over tabs, actual horizontal scroll in document no scroll over tabs. (both official debian packages and your packages)

I guess, when no long lines in document, horizontal scroll event handler is not installed to document view, so when horizontal scroll happens, event will be sent to document view's parent widget, I think, document tab will handle this event, and scroll over tabs happens.

**Comment by sc0w** [comment]
@zhangn1985 please test: [packages_fix349_v2.zip](https://github.com/mate-desktop/pluma/files/2293848/packages_fix349_v2.zip)

**Comment by zhangn1985** [comment]
@sc0w yes, only horizontal.

vertical scroll works well

**Comment by zhangn1985** [comment]
@sc0w your new fix doesn't work.

**Comment by zhangn1985** [comment]
if you don't have this device, I think you can use uinput driver to emulate horizontal scroll device.
https://github.com/tuomasjjrasanen/python-uinput   this is python module for uinput.

I'm still happy to test your new package. but not available next 3 days, I will go travel.

**Comment by sc0w** [comment]
I have a mouse with horizontal scroll and I can't reproduce the issue you mentioned

Are you sure the packages I mentioned don't work? you killed all the previous pluma windows?

**Comment by zhangn1985** [comment]
em,, I can still reproduce it with your new package.

when I say ONLY horizontal, the fact is I can't do pure horizontal scrolling, let me show `xev` result:

```
ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528089, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528089, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528125, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528125, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528175, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528175, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528175, (108,97), root:(120,214),
    state 0x10, button 4, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528175, (108,97), root:(120,214),
    state 0x810, button 4, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528232, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528232, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528255, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528255, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528310, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528310, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonPress event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528352, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES

ButtonRelease event, serial 25, synthetic NO, window 0x3400001,
    root 0x9b, subw 0x0, time 528352, (108,97), root:(120,214),
    state 0x10, button 6, same_screen YES
```

that maybe only happens when mixed scroll

could you tell me how to build and debug it, I want to solve myself.

**Comment by zhangn1985** [comment]
![a](https://user-images.githubusercontent.com/832666/44215986-70911700-a1a6-11e8-9c2c-329baab85d41.gif)

one video more than thousands words.

**Comment by sc0w** [comment]
> first, do you reproduce it with debian official packages?

no

> 2nd, you can't reproduce it with your new packages?

no

I hope now is fixed here, please test: [packages_fix349_v3.zip](https://github.com/mate-desktop/pluma/files/2295575/packages_fix349_v3.zip)

**Comment by zhangn1985** [comment]
@sc0w no, scrolling doesn't work with your v3 packages.

**Comment by sc0w** [comment]
@zhangn1985 the behavior is the same or you see some differences?

**Comment by zhangn1985** [comment]
@sc0w different to v2, scrolling in documents with mouse is OK, but with my keyboard doesn't work, for both vertical and horizontal.

**Comment by sc0w** [comment]
@zhangn1985 please test:

[packages_fix349_v4.zip](https://github.com/mate-desktop/pluma/files/2300848/packages_fix349_v4.zip)

**Comment by zhangn1985** [comment]
@sc0w
 from tester view, when vertical and horizontal scrolling bar are shown, this issue doesn't exist.

I guess, vertical scrolling bar means vertical scrolling signal is connected to pluma view,  horizontal scrolling bar means horizontal scrolling signal is connected to pluma view.

 when both signal  is connected to pluma view then the issue is gone.

how about force to connect these signals to pluma view? will this touch gtksourceview?

**Comment by zhangn1985** [comment]
@sc0w v4 is good. fix this issue.
