### ISSUE TITLE
manual: external URLs point to non-existent page (http://live.gnome.org/...)

### ISSUE THREAD

**Issue by rbuj** [mate-desktop/pluma#375]
https://github.com/mate-desktop/pluma/blob/2cd75f967e55d4d1c558fd308af059b48f71adfc/help/C/index.docbook#L1365

https://github.com/mate-desktop/pluma/blob/2cd75f967e55d4d1c558fd308af059b48f71adfc/help/C/index.docbook#L1410

**Comment by raveit65** [comment]
There are 2 repos at github for pluma-plugins, but they are never updated to gtk+-3 or python3
https://github.com/yselkowitz/pluma-plugins/commits/master
https://github.com/infirit/pluma-plugins/commits/master
No idea if the first repo will work with current pluma. I never tested it.
So i am not sure how well they are maintained and if we should mention them in user-guide.
Thoughts?
@mate-desktop/core-team

**Comment by sc0w** [comment]
I suggest just to remove the affected text.

**Comment by yselkowitz** [comment]
No, pluma plugins is not ported to recent versions of pluma, and unfortunately I have no idea when that will happen.

**Comment by monsta** [comment]
Looks like that text can be safely removed then.

**Comment by monsta** [comment]
The "creating plugins" part can be dropped too - I don't think we have any docs on making the libpeas-based plugins...
