### ISSUE TITLE
Attempting to scroll in a document with no scroll bar switches tabs

### ISSUE THREAD

**Issue by bogger33** [mate-desktop/pluma#382]
#### Expected behaviour

Nothing happens

#### Actual behaviour

It switches to the next tab over

#### Steps to reproduce the behaviour

Press the new document button twice. Focus the text window, scroll

it will now switch between the two documents, and will do so for as long as the current document does not have a scroll bar. This means if you accidentally scroll, or attempt to scroll not realizing that there is no scroll bar, it will switch documents, which can get very annoying

#### MATE general version

(using kde)

#### Package version

Pluma 1.20.2

#### Linux Distribution

debian testing

**Comment by sc0w** [comment]
Do you mean this issue?

https://github.com/mate-desktop/pluma/issues/349#issuecomment-413572946

It was already fixed with https://github.com/mate-desktop/pluma/commit/efc1b02a472a3f63c47b8f4dd51cc4b109e4a5af

Not released new pluma 1.20 version yet with that.

**Comment by bogger33** [comment]
Yes, that does appear to be the same issue, thanks.

**Comment by sc0w** [comment]
@raveit65 is the time to new release in the 1.20 branch?

**Comment by raveit65** [comment]
@sc0w
New release coming soon.

**Comment by raveit65** [comment]
pluma-1.20.3 is released.
