### ISSUE TITLE
[git version] (pluma:5443): GLib-GIO-ERROR **: 19:28:58.233: Settings schema 'org.mate.pluma' does not contain a key named 'show-single-tab' Trace/breakpoint trap

### ISSUE THREAD

**Issue by bogger33** [mate-desktop/pluma#387]
This is probably my fault, sorry if the issue tracker is the wrong place for this, I'm trying to build pluma from source to make a pull request, I did manage to make it compile, but when I run it, it gives me this error:

(pluma:5490): GLib-GIO-ERROR **: 19:31:08.111: Settings schema 'org.mate.pluma' does not contain a key named 'show-single-tab'
Trace/breakpoint trap

I'm guessing I'm just doing something wrong in building it, can someone lend me a hand? I'm trying to take a crack at doing a pull request but I'm probably a little out of my depth to be honest

**Comment by Yetoo1** [comment]
gsettings schema isn't installed in the correct directory. If you used a non-/usr --prefix with configure, try to set GSETTINGS_SCHEMA_DIR to $prefix/share/glib-2.0/schemas. Try placing /usr in palce of $prefix if that initially doesn't work. If that doesn't work, try to use the data folder in the root directory of Pluma's source as the path for the GSETTINGS_SCHEMA_DIR.

**Comment by bogger33** [comment]
I'm still getting the same thing:

$ GSETTINGS_SCHEMA_DIR=/usr/share/glib-2.0/schemas
$ export GSETTINGS_SCHEMA_DIR
$ pluma

I checked the schema there and it actually did not contain the key in question, I think it's from my regular pluma install, maybe I've done something horribly wrong here. I also tried this (with /home/bogger/pluma being the folder i built pluma in):

$ GSETTINGS_SCHEMA_DIR=/home/bogger/pluma/data
$ export GSETTINGS_SCHEMA_DIR
$ pluma

and it still gives me the same thing, but org.mate.pluma.gschema.xml does contain the key in question, so I don't think it's actually referencing it

**Comment by lukefromdc** [comment]
With a normal install and schemas in their normal directory this will happen if they are not recompiled. I don't know anything about how they behave if in another directory though.

**Comment by bogger33** [comment]
so what's the best way to build and run a dev-build of pluma with a system where pluma is also installed?

**Comment by Yetoo1** [comment]
Is the instance of Pluma that is already installed running when you try to run the built executable?

**Comment by lukefromdc** [comment]
All of my dev builds are installed right over my previous versions,  all of which I also build locally and build with the exact same directory options. After I am done a make-uninstall removes them and I can reinstall my locally built Debian package

**Comment by bogger33** [comment]
it didn't seem to work to make install over my existing pluma (I guess because it didn't remove the supporting packages with it), but I uninstalled that and the dev build started working. Thanks for all the help!
