### ISSUE TITLE
Bug in size of snippets Window

### ISSUE THREAD

**Issue by andrewfowlie** [mate-desktop/pluma#391]
#### Expected behaviour

When I select the Tools->Manage Snippets... window, the first time, the size of the window is alright. I expect it to be the size I left it with when I close it then again select Tools->Manage Snippets...

#### Actual behaviour

Any subsequent times I do it the Manage Snippets window is too small to see the contents and I have to manually expand it.

#### Steps to reproduce the behaviour

Tools->Manage Snippets... 
Note the size. Close the window
Tools->Manage Snippets... 
Note the tiny size

#### MATE general version

Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

#### Package version

pluma - Version 1.20.2

#### Linux Distribution

Linux desktop 4.18.0-10-generic #11-Ubuntu SMP Thu Oct 11 15:13:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# Fix

The problem is that the lines to save the current size of the window

https://github.com/mate-desktop/pluma/blob/94b306143618cfbd9a0c8908ea7d47f3a86ef6af/plugins/snippets/snippets/Manager.py#L602-L603

get called after the relevant object gets destroyed

https://github.com/mate-desktop/pluma/blob/94b306143618cfbd9a0c8908ea7d47f3a86ef6af/plugins/snippets/snippets/Manager.py#L616

as a result, a default size of (1, 1) from `get_allocate` on a destroyed object gets returned and used the default. I will push a make a PR with a fix that gets the size before the object gets destroyed.

**Comment by raveit65** [comment]
Confirmed with fedora 28.

**Comment by tamplan** [comment]
This issue should be closed by now.
