### ISSUE TITLE
1.22.1: test suite is core dumping

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/pluma#418]
<pre>make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.22.1/tests&apos;
<font color="#00CD00">PASS</font>: smart-converter
<font color="#00CD00">PASS</font>: document-input-stream
../test-driver: line 107: 23883 Trace/breakpoint trap   (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
<font color="#CD0000">FAIL</font>: document-output-stream
../test-driver: line 107: 23904 Trace/breakpoint trap   (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
<font color="#CD0000">FAIL</font>: document-loader
../test-driver: line 107: 23920 Trace/breakpoint trap   (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
<font color="#CD0000">FAIL</font>: document-saver
<font color="#CD0000">============================================================================</font>
<font color="#CD0000">Testsuite summary for pluma 1.22.1</font>
<font color="#CD0000">============================================================================</font>
<b># TOTAL: 5</b>
<font color="#00CD00"># PASS:  2</font>
# SKIP:  0
# XFAIL: 0
<font color="#CD0000"># FAIL:  3</font>
# XPASS: 0
# ERROR: 0
<font color="#CD0000">============================================================================</font>
<font color="#CD0000">See tests/test-suite.log</font>
<font color="#CD0000">Please report to https://github.com/mate-desktop/pluma/issues</font>
<font color="#CD0000">============================================================================</font>
</pre>

**Comment by raveit65** [comment]
Sadly you ignored template, your report lags of missing information.
I don't get your issues.
```
./configure --enable-tests
<cut>
Configuration:

	Source code location:	.
	Compiler:		gcc
	Spell Plugin enabled:	yes
	Gvfs metadata enabled:	yes
	GObject Introspection:	yes
	Tests enabled:		yes
<cut>
Making all in tests
make[2]: Entering directory '/media/Data-2/Downloads/MATE/pluma-1.22.1/tests'
  CC       smart-converter.o
  CCLD     smart-converter
  CC       document-input-stream.o
  CCLD     document-input-stream
  CC       document-output-stream.o
  CCLD     document-output-stream
  CC       document-loader.o
  CCLD     document-loader
  CC       document-saver.o
  CCLD     document-saver
make[2]: Leaving directory '/media/Data-2/Downloads/MATE/pluma-1.22.1/tests'
```

**Comment by kloczek** [comment]
Closing.
Looks like 1.23.0 is ok now..
