### ISSUE TITLE
Port to Qt Framework (for Lubuntu)

### ISSUE THREAD

**Issue by volomike** [mate-desktop/pluma#419]
I'm on Lubuntu 19.04, which now has a completely recoded desktop in Qt/C++ and runs zippy fast. Is there anyone working on a port of Pluma to the Qt framework?

Things I really want to see:

* The simplicity of Gedit/Pluma
* Line-numbering and indents
* Highlighting matching parenthesis and curly braces
* Code coloring detection (HTML, Javascript, PHP, C, C++, C#, etc.)
* Kobalt color scheme (or comparable dark scheme)
* Project sidepane
* External tools -- because I hook up PHP Lint there (php -l)
* Sort
* Spell Checker
* Right margin feature

**Comment by lukefromdc** [comment]
I don't see any likelihood of any MATE component or application being ported from GTK to QT. MATE is a fork of GNOME 2, which orginally developed hand in hand with GTK2 development. We ported from GTK2 to GTK3 and that was difficult enough.
