### ISSUE TITLE
1.23.1: test suite fails

### ISSUE THREAD

**Issue by kloczek** [mate-desktop/pluma#461]
<pre>+ /usr/bin/make -O -j48 V=1 VERBOSE=1 check
Making check in pluma
/usr/bin/make  check-recursive
Making check in dialogs
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/pluma/dialogs&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./pluma-encodings-dialog.ui ./pluma-preferences-dialog.ui ./pluma-search-dialog.ui; \
        fi
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/pluma/dialogs&apos;
Making check in smclient
make[3]: Nothing to be done for &apos;check&apos;.
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/pluma&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./pluma-print-preferences.ui; \
        fi
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/pluma&apos;
Making check in pixmaps
make[1]: Nothing to be done for &apos;check&apos;.
Making check in po
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/po&apos;
INTLTOOL_EXTRACT=&quot;/usr/bin/intltool-extract&quot; XGETTEXT=&quot;/usr/bin/xgettext&quot; srcdir=. /usr/bin/intltool-update --gettext-package pluma --pot
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/po&apos;
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/po&apos;
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
if [ -r missing -o -r notexist ]; then \
  exit 1; \
fi
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/po&apos;
Making check in data
make[1]: Nothing to be done for &apos;check&apos;.
Making check in plugins
Making check in changecase
make[2]: Nothing to be done for &apos;check&apos;.
Making check in docinfo
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/docinfo&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./docinfo.ui; \
        fi
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/docinfo&apos;
Making check in externaltools
Making check in tools
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/externaltools/tools&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./tools.ui ./outputpanel.ui; \
        fi
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/externaltools/tools&apos;
Making check in data
make[3]: Nothing to be done for &apos;check&apos;.
Making check in scripts
make[3]: Nothing to be done for &apos;check&apos;.
make[3]: Nothing to be done for &apos;check-am&apos;.
Making check in filebrowser
/usr/bin/make  check-am
make[3]: Nothing to be done for &apos;check-am&apos;.
Making check in modelines
make[2]: Nothing to be done for &apos;check&apos;.
Making check in pythonconsole
Making check in pythonconsole
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/pythonconsole/pythonconsole&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./config.ui; \
        fi
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/pythonconsole/pythonconsole&apos;
make[3]: Nothing to be done for &apos;check-am&apos;.
Making check in quickopen
Making check in quickopen
make[3]: Nothing to be done for &apos;check&apos;.
make[3]: Nothing to be done for &apos;check-am&apos;.
Making check in snippets
Making check in snippets
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/snippets/snippets&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./snippets.ui; \
        fi
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/snippets/snippets&apos;
Making check in data
Making check in lang
make[4]: Nothing to be done for &apos;check&apos;.
make[4]: Nothing to be done for &apos;check-am&apos;.
make[3]: Nothing to be done for &apos;check-am&apos;.
Making check in sort
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/sort&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./sort.ui; \
        fi
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/sort&apos;
Making check in taglist
make[2]: Nothing to be done for &apos;check&apos;.
Making check in time
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/time&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./pluma-time-dialog.ui ./pluma-time-setup-dialog.ui; \
        fi
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/time&apos;
Making check in trailsave
make[2]: Nothing to be done for &apos;check&apos;.
Making check in spell
/usr/bin/make  check-am
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/spell&apos;
if [[ true == *gla11y ]]; then \
        python3 true -P ./ -f ./ui-a11y.false -s ./ui-a11y.suppr -o ui-a11y.err ./spell-checker.ui ./languages-dialog.ui ./pluma-spell-setup-dialog.ui; \
        fi
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/plugins/spell&apos;
make[2]: Nothing to be done for &apos;check-am&apos;.
Making check in docs
Making check in reference
make[2]: Nothing to be done for &apos;check&apos;.
make[2]: Nothing to be done for &apos;check-am&apos;.
Making check in help
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/help&apos;
for lc in C  bn zh_HK de gl ky zh_TW zh_CN th ku_IQ mai tr pa en_CA sr es_AR is nl cy mr ms bg lt en_AU ga fa ast ro gu da te ca af be ta hi pl ru mn mg es nb nn uz cs eu ne vi hr crh ur or hy fr sl si fur ie it bs ka sv uk cmn as dz az es_CO sk lv hu pt nds kk br eo kn am ml mk ja fi xh ug el he ar frp en_GB rw oc ps et sq pt_BR ku id sr@latin ca@valencia wa bn_IN ko ; do \
  if test -d &quot;$lc&quot;; \
    then d=; \
    xmlpath=&quot;$lc&quot;; \
  else \
    d=&quot;./&quot;; \
    xmlpath=&quot;$lc:./$lc&quot;; \
  fi; \
  for page in index.docbook legal.xml; do \
    echo &quot;xmllint --nonet --noout --noent --path $xmlpath --xinclude $d$lc/$page&quot;; \
    xmllint --nonet --noout --noent --path &quot;$xmlpath&quot; --xinclude &quot;$d$lc/$page&quot;; \
  done; \
done
xmllint --nonet --noout --noent --path C --xinclude C/index.docbook
xmllint --nonet --noout --noent --path C --xinclude C/legal.xml
xmllint --nonet --noout --noent --path bn --xinclude bn/index.docbook
xmllint --nonet --noout --noent --path bn --xinclude bn/legal.xml
xmllint --nonet --noout --noent --path zh_HK --xinclude zh_HK/index.docbook
xmllint --nonet --noout --noent --path zh_HK --xinclude zh_HK/legal.xml
xmllint --nonet --noout --noent --path de --xinclude de/index.docbook
xmllint --nonet --noout --noent --path de --xinclude de/legal.xml
xmllint --nonet --noout --noent --path gl --xinclude gl/index.docbook
xmllint --nonet --noout --noent --path gl --xinclude gl/legal.xml
xmllint --nonet --noout --noent --path ky --xinclude ky/index.docbook
xmllint --nonet --noout --noent --path ky --xinclude ky/legal.xml
xmllint --nonet --noout --noent --path zh_TW --xinclude zh_TW/index.docbook
xmllint --nonet --noout --noent --path zh_TW --xinclude zh_TW/legal.xml
xmllint --nonet --noout --noent --path zh_CN --xinclude zh_CN/index.docbook
xmllint --nonet --noout --noent --path zh_CN --xinclude zh_CN/legal.xml
xmllint --nonet --noout --noent --path th --xinclude th/index.docbook
xmllint --nonet --noout --noent --path th --xinclude th/legal.xml
xmllint --nonet --noout --noent --path ku_IQ --xinclude ku_IQ/index.docbook
xmllint --nonet --noout --noent --path ku_IQ --xinclude ku_IQ/legal.xml
xmllint --nonet --noout --noent --path mai --xinclude mai/index.docbook
xmllint --nonet --noout --noent --path mai --xinclude mai/legal.xml
xmllint --nonet --noout --noent --path tr --xinclude tr/index.docbook
xmllint --nonet --noout --noent --path tr --xinclude tr/legal.xml
xmllint --nonet --noout --noent --path pa --xinclude pa/index.docbook
xmllint --nonet --noout --noent --path pa --xinclude pa/legal.xml
xmllint --nonet --noout --noent --path en_CA --xinclude en_CA/index.docbook
xmllint --nonet --noout --noent --path en_CA --xinclude en_CA/legal.xml
xmllint --nonet --noout --noent --path sr --xinclude sr/index.docbook
xmllint --nonet --noout --noent --path sr --xinclude sr/legal.xml
xmllint --nonet --noout --noent --path es_AR --xinclude es_AR/index.docbook
xmllint --nonet --noout --noent --path es_AR --xinclude es_AR/legal.xml
xmllint --nonet --noout --noent --path is --xinclude is/index.docbook
xmllint --nonet --noout --noent --path is --xinclude is/legal.xml
xmllint --nonet --noout --noent --path nl --xinclude nl/index.docbook
xmllint --nonet --noout --noent --path nl --xinclude nl/legal.xml
xmllint --nonet --noout --noent --path cy --xinclude cy/index.docbook
xmllint --nonet --noout --noent --path cy --xinclude cy/legal.xml
xmllint --nonet --noout --noent --path mr --xinclude mr/index.docbook
xmllint --nonet --noout --noent --path mr --xinclude mr/legal.xml
xmllint --nonet --noout --noent --path ms --xinclude ms/index.docbook
xmllint --nonet --noout --noent --path ms --xinclude ms/legal.xml
xmllint --nonet --noout --noent --path bg --xinclude bg/index.docbook
xmllint --nonet --noout --noent --path bg --xinclude bg/legal.xml
xmllint --nonet --noout --noent --path lt --xinclude lt/index.docbook
xmllint --nonet --noout --noent --path lt --xinclude lt/legal.xml
xmllint --nonet --noout --noent --path en_AU --xinclude en_AU/index.docbook
xmllint --nonet --noout --noent --path en_AU --xinclude en_AU/legal.xml
xmllint --nonet --noout --noent --path ga --xinclude ga/index.docbook
xmllint --nonet --noout --noent --path ga --xinclude ga/legal.xml
xmllint --nonet --noout --noent --path fa --xinclude fa/index.docbook
xmllint --nonet --noout --noent --path fa --xinclude fa/legal.xml
xmllint --nonet --noout --noent --path ast --xinclude ast/index.docbook
xmllint --nonet --noout --noent --path ast --xinclude ast/legal.xml
xmllint --nonet --noout --noent --path ro --xinclude ro/index.docbook
xmllint --nonet --noout --noent --path ro --xinclude ro/legal.xml
xmllint --nonet --noout --noent --path gu --xinclude gu/index.docbook
xmllint --nonet --noout --noent --path gu --xinclude gu/legal.xml
xmllint --nonet --noout --noent --path da --xinclude da/index.docbook
xmllint --nonet --noout --noent --path da --xinclude da/legal.xml
xmllint --nonet --noout --noent --path te --xinclude te/index.docbook
xmllint --nonet --noout --noent --path te --xinclude te/legal.xml
xmllint --nonet --noout --noent --path ca --xinclude ca/index.docbook
xmllint --nonet --noout --noent --path ca --xinclude ca/legal.xml
xmllint --nonet --noout --noent --path af --xinclude af/index.docbook
xmllint --nonet --noout --noent --path af --xinclude af/legal.xml
xmllint --nonet --noout --noent --path be --xinclude be/index.docbook
xmllint --nonet --noout --noent --path be --xinclude be/legal.xml
xmllint --nonet --noout --noent --path ta --xinclude ta/index.docbook
xmllint --nonet --noout --noent --path ta --xinclude ta/legal.xml
xmllint --nonet --noout --noent --path hi --xinclude hi/index.docbook
xmllint --nonet --noout --noent --path hi --xinclude hi/legal.xml
xmllint --nonet --noout --noent --path pl --xinclude pl/index.docbook
xmllint --nonet --noout --noent --path pl --xinclude pl/legal.xml
xmllint --nonet --noout --noent --path ru --xinclude ru/index.docbook
xmllint --nonet --noout --noent --path ru --xinclude ru/legal.xml
xmllint --nonet --noout --noent --path mn --xinclude mn/index.docbook
xmllint --nonet --noout --noent --path mn --xinclude mn/legal.xml
xmllint --nonet --noout --noent --path mg --xinclude mg/index.docbook
xmllint --nonet --noout --noent --path mg --xinclude mg/legal.xml
xmllint --nonet --noout --noent --path es --xinclude es/index.docbook
xmllint --nonet --noout --noent --path es --xinclude es/legal.xml
xmllint --nonet --noout --noent --path nb --xinclude nb/index.docbook
xmllint --nonet --noout --noent --path nb --xinclude nb/legal.xml
xmllint --nonet --noout --noent --path nn --xinclude nn/index.docbook
xmllint --nonet --noout --noent --path nn --xinclude nn/legal.xml
xmllint --nonet --noout --noent --path uz --xinclude uz/index.docbook
xmllint --nonet --noout --noent --path uz --xinclude uz/legal.xml
xmllint --nonet --noout --noent --path cs --xinclude cs/index.docbook
xmllint --nonet --noout --noent --path cs --xinclude cs/legal.xml
xmllint --nonet --noout --noent --path eu --xinclude eu/index.docbook
xmllint --nonet --noout --noent --path eu --xinclude eu/legal.xml
xmllint --nonet --noout --noent --path ne --xinclude ne/index.docbook
xmllint --nonet --noout --noent --path ne --xinclude ne/legal.xml
xmllint --nonet --noout --noent --path vi --xinclude vi/index.docbook
xmllint --nonet --noout --noent --path vi --xinclude vi/legal.xml
xmllint --nonet --noout --noent --path hr --xinclude hr/index.docbook
xmllint --nonet --noout --noent --path hr --xinclude hr/legal.xml
xmllint --nonet --noout --noent --path crh --xinclude crh/index.docbook
xmllint --nonet --noout --noent --path crh --xinclude crh/legal.xml
xmllint --nonet --noout --noent --path ur --xinclude ur/index.docbook
xmllint --nonet --noout --noent --path ur --xinclude ur/legal.xml
xmllint --nonet --noout --noent --path or --xinclude or/index.docbook
xmllint --nonet --noout --noent --path or --xinclude or/legal.xml
xmllint --nonet --noout --noent --path hy --xinclude hy/index.docbook
xmllint --nonet --noout --noent --path hy --xinclude hy/legal.xml
xmllint --nonet --noout --noent --path fr --xinclude fr/index.docbook
xmllint --nonet --noout --noent --path fr --xinclude fr/legal.xml
xmllint --nonet --noout --noent --path sl --xinclude sl/index.docbook
xmllint --nonet --noout --noent --path sl --xinclude sl/legal.xml
xmllint --nonet --noout --noent --path si --xinclude si/index.docbook
xmllint --nonet --noout --noent --path si --xinclude si/legal.xml
xmllint --nonet --noout --noent --path fur --xinclude fur/index.docbook
xmllint --nonet --noout --noent --path fur --xinclude fur/legal.xml
xmllint --nonet --noout --noent --path ie --xinclude ie/index.docbook
xmllint --nonet --noout --noent --path ie --xinclude ie/legal.xml
xmllint --nonet --noout --noent --path it --xinclude it/index.docbook
xmllint --nonet --noout --noent --path it --xinclude it/legal.xml
xmllint --nonet --noout --noent --path bs --xinclude bs/index.docbook
xmllint --nonet --noout --noent --path bs --xinclude bs/legal.xml
xmllint --nonet --noout --noent --path ka --xinclude ka/index.docbook
xmllint --nonet --noout --noent --path ka --xinclude ka/legal.xml
xmllint --nonet --noout --noent --path sv --xinclude sv/index.docbook
xmllint --nonet --noout --noent --path sv --xinclude sv/legal.xml
xmllint --nonet --noout --noent --path uk --xinclude uk/index.docbook
xmllint --nonet --noout --noent --path uk --xinclude uk/legal.xml
xmllint --nonet --noout --noent --path cmn --xinclude cmn/index.docbook
xmllint --nonet --noout --noent --path cmn --xinclude cmn/legal.xml
xmllint --nonet --noout --noent --path as --xinclude as/index.docbook
xmllint --nonet --noout --noent --path as --xinclude as/legal.xml
xmllint --nonet --noout --noent --path dz --xinclude dz/index.docbook
xmllint --nonet --noout --noent --path dz --xinclude dz/legal.xml
xmllint --nonet --noout --noent --path az --xinclude az/index.docbook
xmllint --nonet --noout --noent --path az --xinclude az/legal.xml
xmllint --nonet --noout --noent --path es_CO --xinclude es_CO/index.docbook
xmllint --nonet --noout --noent --path es_CO --xinclude es_CO/legal.xml
xmllint --nonet --noout --noent --path sk --xinclude sk/index.docbook
xmllint --nonet --noout --noent --path sk --xinclude sk/legal.xml
xmllint --nonet --noout --noent --path lv --xinclude lv/index.docbook
xmllint --nonet --noout --noent --path lv --xinclude lv/legal.xml
xmllint --nonet --noout --noent --path hu --xinclude hu/index.docbook
xmllint --nonet --noout --noent --path hu --xinclude hu/legal.xml
xmllint --nonet --noout --noent --path pt --xinclude pt/index.docbook
xmllint --nonet --noout --noent --path pt --xinclude pt/legal.xml
xmllint --nonet --noout --noent --path nds --xinclude nds/index.docbook
xmllint --nonet --noout --noent --path nds --xinclude nds/legal.xml
xmllint --nonet --noout --noent --path kk --xinclude kk/index.docbook
xmllint --nonet --noout --noent --path kk --xinclude kk/legal.xml
xmllint --nonet --noout --noent --path br --xinclude br/index.docbook
xmllint --nonet --noout --noent --path br --xinclude br/legal.xml
xmllint --nonet --noout --noent --path eo --xinclude eo/index.docbook
xmllint --nonet --noout --noent --path eo --xinclude eo/legal.xml
xmllint --nonet --noout --noent --path kn --xinclude kn/index.docbook
xmllint --nonet --noout --noent --path kn --xinclude kn/legal.xml
xmllint --nonet --noout --noent --path am --xinclude am/index.docbook
xmllint --nonet --noout --noent --path am --xinclude am/legal.xml
xmllint --nonet --noout --noent --path ml --xinclude ml/index.docbook
xmllint --nonet --noout --noent --path ml --xinclude ml/legal.xml
xmllint --nonet --noout --noent --path mk --xinclude mk/index.docbook
xmllint --nonet --noout --noent --path mk --xinclude mk/legal.xml
xmllint --nonet --noout --noent --path ja --xinclude ja/index.docbook
xmllint --nonet --noout --noent --path ja --xinclude ja/legal.xml
xmllint --nonet --noout --noent --path fi --xinclude fi/index.docbook
xmllint --nonet --noout --noent --path fi --xinclude fi/legal.xml
xmllint --nonet --noout --noent --path xh --xinclude xh/index.docbook
xmllint --nonet --noout --noent --path xh --xinclude xh/legal.xml
xmllint --nonet --noout --noent --path ug --xinclude ug/index.docbook
xmllint --nonet --noout --noent --path ug --xinclude ug/legal.xml
xmllint --nonet --noout --noent --path el --xinclude el/index.docbook
xmllint --nonet --noout --noent --path el --xinclude el/legal.xml
xmllint --nonet --noout --noent --path he --xinclude he/index.docbook
xmllint --nonet --noout --noent --path he --xinclude he/legal.xml
xmllint --nonet --noout --noent --path ar --xinclude ar/index.docbook
xmllint --nonet --noout --noent --path ar --xinclude ar/legal.xml
xmllint --nonet --noout --noent --path frp --xinclude frp/index.docbook
xmllint --nonet --noout --noent --path frp --xinclude frp/legal.xml
xmllint --nonet --noout --noent --path en_GB --xinclude en_GB/index.docbook
xmllint --nonet --noout --noent --path en_GB --xinclude en_GB/legal.xml
xmllint --nonet --noout --noent --path rw --xinclude rw/index.docbook
xmllint --nonet --noout --noent --path rw --xinclude rw/legal.xml
xmllint --nonet --noout --noent --path oc --xinclude oc/index.docbook
xmllint --nonet --noout --noent --path oc --xinclude oc/legal.xml
xmllint --nonet --noout --noent --path ps --xinclude ps/index.docbook
xmllint --nonet --noout --noent --path ps --xinclude ps/legal.xml
xmllint --nonet --noout --noent --path et --xinclude et/index.docbook
xmllint --nonet --noout --noent --path et --xinclude et/legal.xml
xmllint --nonet --noout --noent --path sq --xinclude sq/index.docbook
xmllint --nonet --noout --noent --path sq --xinclude sq/legal.xml
xmllint --nonet --noout --noent --path pt_BR --xinclude pt_BR/index.docbook
xmllint --nonet --noout --noent --path pt_BR --xinclude pt_BR/legal.xml
xmllint --nonet --noout --noent --path ku --xinclude ku/index.docbook
xmllint --nonet --noout --noent --path ku --xinclude ku/legal.xml
xmllint --nonet --noout --noent --path id --xinclude id/index.docbook
xmllint --nonet --noout --noent --path id --xinclude id/legal.xml
xmllint --nonet --noout --noent --path sr@latin --xinclude sr@latin/index.docbook
xmllint --nonet --noout --noent --path sr@latin --xinclude sr@latin/legal.xml
xmllint --nonet --noout --noent --path ca@valencia --xinclude ca@valencia/index.docbook
xmllint --nonet --noout --noent --path ca@valencia --xinclude ca@valencia/legal.xml
xmllint --nonet --noout --noent --path wa --xinclude wa/index.docbook
xmllint --nonet --noout --noent --path wa --xinclude wa/legal.xml
xmllint --nonet --noout --noent --path bn_IN --xinclude bn_IN/index.docbook
xmllint --nonet --noout --noent --path bn_IN --xinclude bn_IN/legal.xml
xmllint --nonet --noout --noent --path ko --xinclude ko/index.docbook
xmllint --nonet --noout --noent --path ko --xinclude ko/legal.xml
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/help&apos;
Making check in tests
/usr/bin/make  check-TESTS
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
PASS: smart-converter
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
PASS: document-input-stream
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
../test-driver: line 107: 42328 Trace/breakpoint trap   (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
FAIL: document-loader
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
../test-driver: line 107: 42327 Trace/breakpoint trap   (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
FAIL: document-saver
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
../test-driver: line 107: 42325 Trace/breakpoint trap   (core dumped) &quot;$@&quot; &gt; $log_file 2&gt;&amp;1
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
FAIL: document-output-stream
make[3]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
make[3]: *** [Makefile:800: test-suite.log] Error 1
make[3]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/pluma-1.23.1/tests&apos;
========================================
   pluma 1.23.1: tests/test-suite.log
========================================

# TOTAL: 5
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: document-output-stream
============================

# random seed: R02S0c7164eb6229dcd0483539c0c574c8e7
Bail out! GLib-GIO-FATAL-ERROR: Settings schema &apos;org.mate.pluma&apos; is not installed

(./document-output-stream:42325): GLib-GIO-ERROR **: 05:01:23.164: Settings schema &apos;org.mate.pluma&apos; is not installed
FAIL document-output-stream (exit status: 133)

FAIL: document-loader
=====================

# random seed: R02S5446eef477a0d3baf891dc9366c764f7
Bail out! GLib-GIO-FATAL-ERROR: Settings schema &apos;org.mate.pluma&apos; is not installed

(./document-loader:42328): GLib-GIO-ERROR **: 05:01:23.164: Settings schema &apos;org.mate.pluma&apos; is not installed
FAIL document-loader (exit status: 133)

FAIL: document-saver
====================

# random seed: R02Sc70a142291f3bc5fcb0b1d7aa25e26ab
Bail out! GLib-GIO-FATAL-ERROR: Settings schema &apos;org.mate.pluma&apos; is not installed

(./document-saver:42327): GLib-GIO-ERROR **: 05:01:23.162: Settings schema &apos;org.mate.pluma&apos; is not installed
FAIL document-saver (exit status: 133)

============================================================================
Testsuite summary for pluma 1.23.1
============================================================================
# TOTAL: 5
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to https://github.com/mate-desktop/pluma/issues
============================================================================
</pre>

**Comment by lukefromdc** [comment]
You are getting failures from a schema not being installed(or installed but not detected-maybe you need to recompile schemas?), I can see this happening if Pluma is not installed or is installed to an unusual directory. That should not mess up a preinstall test, but that does not mean it doesn't.  Try installing the exact same version of Pluma first and then retesting, if your experience matches mine you will get another, different error but not this schema issue. What I got is below:
```

FAIL: document-saver
====================

# random seed: R02S82ecb4c7c42063962f5491614e4f6988
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?

***
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ?gio-vfs?
*** Checking for unowned directory test... NO: directory does not exist
*** Checking for unowned group test... NO: file does not exist
***

1..6
# Start of document-saver tests
ok 1 /document-saver/local
ok 2 /document-saver/local-new-line
**
ERROR:document-saver.c:158:mount_ready_callback: assertion failed (error == NULL): Connection refused by server (g-io-error-quark, 39)
Bail out! ERROR:document-saver.c:158:mount_ready_callback: assertion failed (error == NULL): Connection refused by server (g-io-error-quark, 39)
FAIL document-saver (exit status: 134)

============================================================================
Testsuite summary for pluma 1.23.1
============================================================================
# TOTAL: 5
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to https://github.com/mate-desktop/pluma/issues
============================================================================
make[3]: *** [Makefile:801: test-suite.log] Error 1
make[3]: Leaving directory '/home/luke/Desktop/pluma_1.23.1/tests'
make[2]: *** [Makefile:909: check-TESTS] Error 2
make[1]: *** [Makefile:1010: check-am] Error 2
make: *** [Makefile:534: check-recursive] Error 1
luke@ubuntu:~/Desktop/pluma_1.23.1$ 

```

**Comment by kloczek** [comment]
Don't you think that it is a bit strange way of testing which is fired in build tree but relays on resources already installed in system image?

**Comment by lukefromdc** [comment]
No idea, I myself don't normally use it in my builds and this is actually
the first I found Pluma even had it.
