### ISSUE TITLE
GTK3: print preview does not show any content

### ISSUE THREAD

**Issue by infirit** [mate-desktop/pluma#47]
The label changes but no preview is shown.
![pluma-no-print-preview](https://f.cloud.github.com/assets/3465730/1548579/4035da5e-4dce-11e3-9197-fcb07886070c.png)

**Comment by raveit65** [comment]
Huh, two commits with different ids :question: 
Which one should i test  :question:

**Comment by monsta** [comment]
The one that belongs to a branch and to https://github.com/mate-desktop/pluma/pull/150, https://github.com/mate-desktop/pluma/commit/385ec7a3f0e8938206813c17142a8beab5955191 :smile:
The other one was there before I've made another commit with indent fix, squashed them with interactive rebase and force-pushed the new commit.
