### ISSUE TITLE
[translation] What "draw" means?

### ISSUE THREAD

**Issue by sbadux** [mate-desktop/pluma#497]
Hello,
I'm translating MATE in italian. It's almost done and only 15 strings of Pluma are missing. I can't understand what the "draw" function means.

Like:
Draw newline
Draw nbsp
Draw tabs
Draw spaces

What are they used for? I can't find them in Pluma 1.22.1

**Comment by vkareh** [comment]
@sbadux, it means that a character representing newlines (or nbsp, tabs, spaces) is drawn in the pluma view. The closest synonym I can think of is "show" (or maybe "display"):
* Show newline
* Show nbsp
* Show tabs
* Show spaces

(maybe we should change this from Draw to Show? @mate-desktop/core-team ?)

**Comment by sbadux** [comment]
Thanks a lot. Now it's more clear how to translate them. 

IMHO "show" would be better for a non-technical user

**Comment by raveit65** [comment]
show +1

**Comment by vkareh** [comment]
Submitted a patch to change to Show: #498

**Comment by sbadux** [comment]
> Submitted a patch to change to Show: #498

Thanks. Only for my information, the new "Show" strings will be available in transifex soon? I think I need to re-translate them. It's not urgent, i only would like to know if they will available in 1 week, 1 month or 1 year :)

**Comment by vkareh** [comment]
I don't know how transifex works, but once #498 is merged, it should be available in the `master` branch immediately, and next time we do a release (which would likely be 1.23.3), then you'll have access to it there - that can be within 1 week to 1 month... hopefully not a year (although it _could_ happen) :stuck_out_tongue:

**Comment by raveit65** [comment]
We can push a new generated pluma.pot file to transifex after https://github.com/mate-desktop/pluma/pull/498 is merged, np.

**Comment by sc0w** [comment]
@sbadux

![2019-08-22_22-27](https://user-images.githubusercontent.com/7734191/63547319-2e728200-c52c-11e9-95d1-f8c710cd6a1e.png)

**Comment by sbadux** [comment]
Thanks a lot!

**Comment by vkareh** [comment]
@sbadux, #498 has been merged. I'll close this for now. Thanks!
