### ISSUE TITLE
Lost color coding with pluma and vte 0.58

### ISSUE THREAD

**Issue by texstar** [mate-desktop/pluma#505]
#### Expected behaviour
Expected to see color coding

#### Actual behaviour
See plain text

#### Steps to reproduce the behaviour
update to vte 0.58 and rebuild pluma against it.

#### MATE general version
1.22.2

#### Package version
1.22.1

#### Linux Distribution
PCLinuxOS 2019.09

#### Link to downstream report of your Distribution
none

**Comment by lukefromdc** [comment]
VTE? Do you mean color coding in the terminal? If so, that's mate-terminal, a different package

**Comment by texstar** [comment]
Closing this issue. I had gtksouceview 4 and libgtksourceview3 installed that was breaking the colors in pluma when viewing spec files and bash scripts.
