### ISSUE TITLE
Pluma: unable to enable plugins External tools, Python Console, Quick Open, Snippets) because of missed /usr/lib/x86_64-linux-gnu/libpeas-1.0/loaders/libpythonloader.so

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/pluma#508]
#### Expected behaviour
* all plugins are enabled without errors or warnings;

#### Actual behaviour
* plugin(s) are not enabled, show the following errors in `pluma`'s terminal:

```
$ pluma

(pluma:1685): libpeas-WARNING **: 19:20:59.204: Failed to load module 'pythonloader': /usr/lib/x86_64-linux-gnu/libpeas-1.0/loaders/libpythonloader.so: cannot open shared object file: No such file or directory

(pluma:1685): libpeas-WARNING **: 19:20:59.205: Could not load plugin loader 'python'
```

Notes: 

1. in previous releases the `libpythonloader.so` was located in `libpeas-1.0-python2loader package (see https://packages.ubuntu.com/search?suite=disco&arch=amd64&mode=exactfilename&searchon=contents&keywords=libpythonloader.so ) but this file is missed in 19.10 repository.
1. Quick and dirty has is to create a symlink between new file name `libpython2loader.so` (see https://packages.ubuntu.com/eoan/amd64/libpeas-1.0-python2loader/filelist ) and expected old one (see https://packages.ubuntu.com/disco/amd64/libpeas-1.0-python2loader/filelist ):

       sudo ln -s /usr/lib/x86_64-linux-gnu/libpeas-1.0/loaders/libpython2loader.so /usr/lib/x86_64-linux-gnu/libpeas-1.0/loaders/libpythonloader.so

#### Steps to reproduce the behaviour
1. Install Ubuntu 19.10
2. Launch Pluma
3. Go to Edit -> Preferences, switch to Plugins tab
4. Try enable all plugins by checking their checkmarks

#### MATE general version
1.22.2

#### Package version
1.22.2-0ubuntu1

#### Linux Distribution
Ubuntu 19.10 (development branch)

#### Link to downstream report of your Distribution
https://bugs.launchpad.net/bugs/1846890

**Comment by monsta** [comment]
Ok, I forgot about this one... In addition to the patch in Ubuntu 19.10, it's also fixed in libpeas 1.24.1 upstream (https://github.com/GNOME/libpeas/commit/d012f7b4ff98ed26c74788696b652c65ea2884cd).
