### ISSUE TITLE
Mouse wheel should not switch between tabs

### ISSUE THREAD

**Issue by catmatist** [mate-desktop/pluma#515]
#### Expected behaviour
If I have the mouse pointer over the content area of a tab and use the mouse vertical scroll wheel, it should scroll the contents up or down if possible. When the top or bottom of the file is reached, continuing to move the mouse wheel in the same direction should do nothing.

#### Actual behaviour
When the top or bottom of the file is reached, continuing to move the mouse wheel in the same direction switches from tab to tab until you stop moving the wheel. When working on similar looking files in different tabs, this is not just inconvenient, it is catastrophic.

#### Steps to reproduce the behaviour
Use multiple tabs in a Pluma window and spin the scroll wheel.

#### Package version
Pluma 1.20.1

#### Linux Distribution
Ubuntu-MATE 18.04

**Comment by lukefromdc** [comment]
I just tested for this, and I was unable to duplicate this on pluma 1.23  from git master over Debian Unstable, and have never seen it though I don't normally use the scroll wheel on the document area so just tested this. Thus I don't know for sure if this problem existed on my system in the past and was fixed by a pluma or GTK3 change, or if I never has it but the latter seems likely.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/pluma/commit/ed34d929a420da68b49e232a08bc3ca8f980200c
https://github.com/mate-desktop/pluma/commit/cced651e89d44f2119fd0fe29435141e4d57bbe8
> #### Link to downstream report of your Distribution

Closing, already fixed, solution is not to ignore our template and filling out an upstream bug first at ubuntu for asking ubuntu manitainer to add this commits to pluma or updating to 1.22.

**Comment by catmatist** [comment]
If we are being persnickety, Ubuntu is downstream from Pluma, not upstream, is it not? Depending on what kind of stream you are talking about, of course.

**Comment by raveit65** [comment]
typo, of course ubuntu is downstream.
In any case  we can't fix what already is fixed :)

**Comment by BrentBradburn** [comment]
Demo: https://github.com/mate-desktop/pluma/issues/349#issuecomment-413572946
Fixed as of 1.20.3 and 1.21.2: https://github.com/mate-desktop/pluma/issues/382
