### ISSUE TITLE
Does not build from AUR or from clone.

### ISSUE THREAD

**Issue by xircon** [mate-desktop/pluma#519]
#### Expected behaviour
It build

#### Actual behaviour
```
configure.ac:25: installing './missing'
Makefile.am: installing './INSTALL'
plugins/changecase/Makefile.am: installing './depcomp'
plugins/externaltools/tools/Makefile.am:4: installing './py-compile'
pluma/Makefile.am:199: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
```

#### Steps to reproduce the behaviour
Clone or build  from AUR

#### MATE general version
1.22.1-1

#### Package version
?

#### Linux Distribution
Manjaro

#### Link to downstream report of your Distribution
https://forum.manjaro.org/t/pluma-python3-does-not-build/122943

**Comment by raveit65** [comment]
You need to build pluma with python3 patches from this branch.
https://github.com/mate-desktop/pluma/commits/python3-1.22
This is what i use for fedora since 3/4 years ;)
https://src.fedoraproject.org/rpms/pluma/tree/f31
I thought Manjaro maintainer always follow my my fedora rpms.
Or use pluma-1.23.x dev versions.
Or wait for Mate-1.24......

**Comment by xircon** [comment]
Same problem:
```
git clone --single-branch --branch python3-1.22 https://github.com/mate-desktop/pluma.git
```
Makefile.am: installing './INSTALL'
plugins/changecase/Makefile.am: installing './depcomp'
plugins/externaltools/tools/Makefile.am:4: installing './py-compile'
pluma/Makefile.am:196: error: HAVE_INTROSPECTION does not appear in AM_CONDITIONAL
parallel-tests: installing './test-driver'
autoreconf: automake failed with exit status: 1
```

**Comment by xircon** [comment]
I was missing gobject-introspection

**Comment by xircon** [comment]
I was missing gobject-introspection
