### ISSUE TITLE
Pluma ignores interface consistency

### ISSUE THREAD

**Issue by jEsuSdA** [mate-desktop/pluma#525]
#### Expected behaviour

When opening Pluma I spect to have a uniform look with the same font size in all GTK apps.

Here is how Pluma 1.20 looks:

![imagen](https://user-images.githubusercontent.com/5833446/74736336-c8548680-5252-11ea-9c76-23f6df0e2035.png)

All the interface looks as expected and with the fonts in correct size.

#### Actual behaviour

But in 1.22 and 1.24 versions I get this:

![imagen](https://user-images.githubusercontent.com/5833446/74735958-0b622a00-5252-11ea-82f2-0f48a2b0d934.png)

Pluma ignores all the configuration about fonts. Not the same font family and not the same font size. So it looks like more similar to Frankenstein than the rest of my apps XD.

#### Steps to reproduce the behaviour
Here is my GTK configuration:

![imagen](https://user-images.githubusercontent.com/5833446/74736003-20d75400-5252-11ea-97e0-72573ae36851.png)

![imagen](https://user-images.githubusercontent.com/5833446/74736045-35b3e780-5252-11ea-891c-beab4ac8e5bd.png)

![imagen](https://user-images.githubusercontent.com/5833446/74736130-61cf6880-5252-11ea-8a26-dbe1365b33e3.png)

#### MATE general version
2.24

#### Package version
1.24.0-1

#### Linux Distribution
Debian Testing

I hope you could solve this. It is very annoying not to be able to upgrade pluma since 1.20 version.
Thanks a lot!

**Comment by BwackNinja** [comment]
I encountered this issue today. The source is: https://github.com/mate-desktop/pluma/commit/ca00615b510549a4abfe44f7b1f97485e1e9f804, which then changes all labels in the application based on the font set in org.mate.interface -> "font-name" (/org/mate/desktop/interface/font-name), overriding any changes done set elsewhere, including the css of your gtk theme.

The goal of that logic is to avoid setting the font on the context menu to monospace, but given the equivalent gedit code, https://github.com/GNOME/gedit/blob/master/gedit/gedit-view.c that's unnecessary.

I'll write a patch for it sometime this week unless someone else beats me to it.

**Comment by jEsuSdA** [comment]
Thank you so much for researching about this bug. I hope this could be fixed soon. 

Thanks a lot!

**Comment by BwackNinja** [comment]
I created https://github.com/mate-desktop/pluma/pull/582 if you'd like to test my changes.

**Comment by raveit65** [comment]
For stable branch https://github.com/mate-desktop/pluma/commit/1b879ef459cce5d6012c9f535b2ce2f056b49989
