### ISSUE TITLE
No help or documentation on regex format and syntax

### ISSUE THREAD

**Issue by superian** [mate-desktop/pluma#538]
I wanted to search a file in Pluma for a regular expression. I can't remember which regex syntax it uses, but ^ for 'start of line' doesn't work. OK, let's _look it up_.

#### Expected behaviour

Being able to find it in help
Being able to find it in the man file
Being able to find it on wiki.mate-desktop.org

#### Actual behaviour

The application help does not mention regular expressions at all. "Finding Text" says there are some 'special characters', but those are only \n, \t, \r, and \\. "Find and Replace Options" doesn't mention the regular expressions option that's been there for a while.

The main file is about the command line, rather than using the editor. It suggests "Further information may also be available at: http://wiki.mate-desk-top.org/docs". That URL no longer exists.

wiki.mate-desk-top.org - hmm, where is it? Documentation? There's a list of some MATE applications there, but not Pluma. Applications? Pluma is listed, but that's all and there's no linked to page(s) on it. No other pages seem to have anything, and the wiki reckons the current stable and development versions are 1.22 and 1.23.

OK, do a Google search for 

`"pluma" "regex"`

Nine pages of results, nothing useful on the first page, and nothing obviously useful on the other eight.

`"pluma" "regular expression"`

Eight pages, ditto.

#### MATE general version
1.24

#### Package version
1.24

#### Linux Distribution
Ubuntu MATE 20.04 LTS beta

**Comment by rbuj** [comment]
`^` works as expected. I can't reproduce your issue.

test.txt
```
11.aaa 222
11 aa 222
 11 aaa 222
11

^\d{2}\.\w{3}+.*
```

regex: `^\d{2}\.\w{3}+.*`

<img width="707" alt="Captura de Pantalla 2020-04-16 a les 18 51 19" src="https://user-images.githubusercontent.com/10171411/79484275-ae95ac80-8013-11ea-92c7-ca83f3ee40f9.png">

**Comment by superian** [comment]
It's lovely that it works for you. It doesn't here

`^def`

should find 'def' at the start of a line, right?

Given a file of 

```
abcdef
defabc
xyzabc

```

It should find the text on the second line. It doesn't.

![not-the-issue](https://user-images.githubusercontent.com/4901677/79487496-3974a800-8010-11ea-8113-b2a5a707bb5e.jpg)

`def$`

doesn't find the text in the second line either. But

`[d-f]` 

works for finding each d/e/f - so it is doing a regex search.

**BUT the issue here is that there is zero about this in the help, in the man page, and on the wiki.**

**Comment by superian** [comment]
Yes :) I don't know if the failure to use the ^ 'start of line' regex character is a bug in the search or a feature of the syntax it's using, because I can't find what the syntax actually is in the obvious places to look. Or anywhere, without looking at the source code + that of any dependencies.

**Comment by rbuj** [comment]
@superian The regex syntax is available at https://developer.gnome.org/glib/stable/glib-regex-syntax.html

**Comment by rbuj** [comment]
multiline mode can be enabled adding `(?m)` in the search [pattern](https://www.pcre.org/original/doc/html/pcrepattern.html) or modifying the source code
```patch
diff --git a/pluma/pluma-utils.c b/pluma/pluma-utils.c
index 761d0c7..da71e68 100644
--- a/pluma/pluma-utils.c
+++ b/pluma/pluma-utils.c
@@ -1573,7 +1573,7 @@ pluma_gtk_text_iter_regex_search (const GtkTextIter *iter,
        gboolean found;
 
        match_string = "";
-       compile_flags = 0;
+       compile_flags = G_REGEX_MULTILINE;
 
        if ((flags & GTK_TEXT_SEARCH_CASE_INSENSITIVE) != 0)
                compile_flags |= G_REGEX_CASELESS;
```

**Comment by superian** [comment]
Thanks, but that's not in the program's documentation either :)

I've opened another issue about that aspect, but saying 'modify the source code' is not a realistic option for most users. If I submitted a request with it done, would it be accepted?

**Comment by superian** [comment]
Thank you.
