### ISSUE TITLE
[RPMLint] 64bit portability issue

### ISSUE THREAD

**Issue by posophe** [mate-desktop/pluma#56]
```
pluma 64bit-portability-issue pluma-style-scheme-manager.c:98, 99, 149, 318, 325, 369 
pluma 64bit-portability-issue pluma.c:1321
```

**Comment by monsta** [comment]
@posophe: yes, because the code has been changed since then, so it's not easy to find out where's the problem without the function names.

**Comment by NiceandGently** [comment]
@posophe 
I didn't find any documentaton about this rpmlint error.
Do you have some?

**Comment by posophe** [comment]
Commonly, the problem comes from a function ( like long long), a pointer, which is only 32-bits compatible and not portable on 64bits.

**Comment by monsta** [comment]
As I said before, we need the exact function names so we won't have to search through the code that had been modified a lot since you've posted this issue...

**Comment by posophe** [comment]
It has been fixed, as I can see. The package build normally, now

**Comment by monsta** [comment]
Ok good, you can close this issue then.

**Comment by monsta** [comment]
@flexiondotorg: please close this, it's resolved now.
