### ISSUE TITLE
Interline editing eats posterior letters

### ISSUE THREAD

**Issue by Porrumentzio** [mate-desktop/pluma#572]
#### Expected behaviour
Editing a word into a line should work without eating any other posterior characters .

#### Actual behaviour
Editing a word into a line eats posterior characters .
![Pluma-eats-posterior-characters](https://user-images.githubusercontent.com/61913683/92236784-6ab61d80-eeb6-11ea-9385-f64d8ad1ec9d.gif)

Saving an opening again the file solves it.

#### Steps to reproduce the behaviour
I have seen no repetitive patron. This time happened on an XML file when pasting a text from browser via selection-clipboard.

#### MATE general version
1.24

#### Package version
1.24

#### Linux Distribution
Manjaro Linux (Arch derivated)

**Comment by vkareh** [comment]
Press the <kbd>Insert</kbd> key and try again... 

![-Unsaved Document 1 - Pluma_003](https://user-images.githubusercontent.com/259780/92237294-1a729780-ee85-11ea-8319-77b0c47db5b4.png)

That indicator on the bottom-right should toggle between `INS` (insert) and `OVR` (overwrite)

**Comment by Porrumentzio** [comment]
So it could be my fault, pressing Insert by accident?

**Comment by vkareh** [comment]
:man_shrugging: 

Try and see if that fixes it?

**Comment by Porrumentzio** [comment]
If it happens again, I'll try that. Thanks @vkareh!

**Comment by vkareh** [comment]
you're welcome :)

I'll close this for now - let me know if it happens again and the <kbd>Insert</kbd> doesn't fix it
