### ISSUE TITLE
Translation of windows is incorrect

### ISSUE THREAD

**Issue by kretcheu** [mate-desktop/pluma#576]
Windows as operating systems was translated as object windows, "Janelas" in Portuguese.
Windows should not be translated.

https://github.com/mate-desktop/pluma/blob/bba42125fb0d1dd10246e20e0b1156b5c40620f7/po/pt_BR.po#L1619

**Comment by raveit65** [comment]
We use transifex server for our translations
Please become a member of you language group and fix the translation there.
Every change here will be override by a pull from transifex.
https://www.transifex.com/mate/MATE/dashboard/
Thank you
