### ISSUE TITLE
File -> Open: no '.hidden' files or subdirs listed

### ISSUE THREAD

**Issue by gandsnut** [mate-desktop/pluma#586]
#### Expected behaviour
Open Pluma
Choose "File -> Open";  dialog opens
Dialog lists current directory AND .filenames (if any) AND .subdirs (if any)
User can choose .filename to edit, or navigate into .subdir to see further files

#### Actual behaviour
Open Pluma
Choose "File -> Open"; dialog opens
Dialog lists current directory 'normal' filenames and subdirs

#### Steps to reproduce the behaviour
Steps spelled out above

#### MATE general version
1.20.1-2ubuntu1      (mate-desktop)

#### Package version
1.20.1-3ubuntu1

#### Linux Distribution
Kernel:  5.4.0-53-generic
Gnome: 3.28.2
Ubuntu: 5.4.0-53-generic #59~18.04.1-Ubuntu SMP Wed Oct 21 12:14:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
![pluma_file_open_dialog](https://user-images.githubusercontent.com/29338195/99882874-213dba80-2be9-11eb-8248-00087e2fde90.png)

**Comment by lukefromdc** [comment]
This is controlled for all applications at once by a filechooser setting in GTK itself. Install dconf-editor if you don't already have it, and go to org>gtk>settings>filechooser and set show_hidden to TRUE.

**Comment by cwendling** [comment]
…or right click and enable "_Show hidden files_", or use <kbd>Ctrl+H</kbd>, or manually edit the location bar with <kbd>Ctrl+L</kbd>…
