### ISSUE TITLE
pluma: issues with Russian localization - not translated items

### ISSUE THREAD

**Issue by HectorB-2020** [mate-desktop/pluma#656]
#### Expected behaviour
Menu "**Edit**" (RU: "**Правка**"), "**Preferences**" (RU: "**Параметры**"), dialog "**Pluma Preferences**" (RU: "**Параметры Pluma**")

Tab "**View**" (RU: "**Вид**")
 - Highlighting 
 - Display right margin at column
 - Display grid pattern
 - Display overview map
_All four items above should be translated to Russian._

Tab "**Editor**" (RU: "**Редактор**")
 - Show Spaces, Tabs, Newlines
_The line above should be translated to Russian._

#### Actual behaviour
Even with
```
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU.UTF-8
```
the mentioned above strings are left in English.

#### Steps to reproduce the behaviour
Run `pluma`, click on menu "**Edit**" , open "**Preferences**", then tabs "**View**" and "**Editor**".

#### MATE general version
MATE 1.26.0

#### Package version
1.26.0

#### Linux Distribution
Ubuntu 21.10 with latest updates.

**Comment by raveit65** [comment]
Again, we're using transifex for our translations. We can't fix it here !
Please become a member of your language team at transifix and fix translations there.
https://www.transifex.com/mate/MATE/languages/
