### ISSUE TITLE
Text formating/coloring doesnt work after update debian bookworm

### ISSUE THREAD

**Issue by Stormfinger** [mate-desktop/pluma#666]
#### Expected behaviour
coloring for css should work

#### Actual behaviour
everything is plain text

#### Steps to reproduce the behaviour
update debian bookworm i didnt change any settings

#### MATE general version
latest in bookworm

#### Package version
1.26.0-1 amd64

#### Linux Distribution
debian bookworm

**Comment by lukefromdc** [comment]
After my last glib and GtkSourceView updates I had to recompile caja to get that to work, sounds like Debian needs to do the same in Bookworm
