### ISSUE TITLE
Dimming makes Pluma unusable

### ISSUE THREAD

**Issue by jethornton** [mate-desktop/pluma#669]
#### Expected behavior
Open two pluma windows and you should be able read both

#### Actual behavior
Open two pluma windows and only the one that has focus is readable

#### Steps to reproduce the behavior
open two pluma windows

#### MATE general version
no clue

#### Package version
1.26.0

#### Linux Distribution
Most debian versions

#### Link to bugreport of your Distribution (requirement)
no clue what this is

The only solution I've found is:
sudo apt remove pluma
sudo apt install geany

**Comment by lukefromdc** [comment]
What GTK theme are you using? This is entirely controlled by your GTK theme. No MATE theme dims Pluma like
this, and I didn't even see dimming of a non-focussed Pluma window in Adwaita (GTK3 default theme).

**Comment by jethornton** [comment]
Yep I finally figured out it was the theme... sorry for the static.
