### ISSUE TITLE
DBUS Id for Pluma ??

### ISSUE THREAD

**Issue by CapeCrusader321** [mate-desktop/pluma#677]
Hey there community, can anyone tell me whats the correct dbus id for pluma ?? is this correct org.mate.pluma ??

**Comment by zhuyaliang** [comment]
```org.mate.pluma``` is the application settings for ```Pluma```, and to my knowledge, ```Pluma``` does not have a ```dbus```

**Comment by CapeCrusader321** [comment]
> `org.mate.pluma` is the application settings for `Pluma`, and to my knowledge, `Pluma` does not have a `dbus`

Is this same for atril ??

**Comment by zhuyaliang** [comment]
```Atri```
![2023-06-09 11-17-29屏幕截图](https://github.com/mate-desktop/pluma/assets/36913152/16c99007-901e-4eb6-8736-7fd785243859)
l owns dbus

**Comment by zhuyaliang** [comment]
[atril-dbus](https://github.com/mate-desktop/atril/blob/master/shell/ev-daemon-gdbus.xml)

**Comment by CapeCrusader321** [comment]
@zhuyaliang Thank you very much for the clarifaction 👍🏻
