### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by golu7679** [mate-desktop/pluma#681]
#### Expected behaviour
Does pluma support Typescript?

#### Steps to reproduce the behaviour
![image](https://github.com/mate-desktop/pluma/assets/55990159/c670eb84-9e50-42c3-a3ff-83abb0975ae1)

When I click on bottom right language select button then their is no option for typescript.

#### MATE general version
1.24.1

**Comment by lukefromdc** [comment]
Pretty sure that's controlled by what GtkSourceView supports

**Comment by golu7679** [comment]
can you add support for typescript language?

**Comment by lukefromdc** [comment]
We are not the maintainers of GtkSourceView, GNOME is
https://gitlab.gnome.org/GNOME/gtksourceview

**Comment by golu7679** [comment]
I think they support typescript https://gitlab.gnome.org/GNOME/gtksourceview/-/blob/master/data/language-specs/typescript.lang

**Comment by lukefromdc** [comment]
In which version? We are using GtkSourceView 4, last tagged version is 5.9.0. Changing major versions
of an underlying library usually involves some porting work. I do not know much about this part of the code,
so I do not know if the newer versions require GTK4 (poorly suited to MATE) or not.

https://wiki.gnome.org/Projects/GtkSourceView

**Comment by golu7679** [comment]
okay

**Comment by lukefromdc** [comment]
First tagged release after the commit you mention is 5.4.2
https://gitlab.gnome.org/GNOME/gtksourceview/-/tags/5.4.2
while we are on the major version 4 series (I have 4.8.4 on Debian Unstable here)

**Comment by lukefromdc** [comment]
Installing libgtksourceview-5-dev on Debian Unstable also requires installing libgtk-4-dev, indicating the package is only usable with Gtk4 which we will not be porting to anytime soon. This makes sense, as libgtksourceview extends GtkTextView, meaning it has to be compatable with the GTK version in use.

For us to ever support typescript or anything else not now in libgtksourceview-4, GNOME would have to backport commits supporting them. If they did, such support would automatically be added simply by using any version of libgtksourceview-4 released after that backport, with no change on our part.

Closing as there is nothing we can do on this end short of a Gtk4 port

**Comment by golu7679** [comment]
okay Thankx
