### ISSUE TITLE
icon problem

### ISSUE THREAD

**Issue by JvGods** [mate-desktop/pluma#688]
#### Expected behaviour
When exiting the remmina main window, click on the icon in the desktop tray to open the remmina program again

#### Actual behaviour
Clicking the tray icon will not open the program

#### Steps to reproduce the behaviour
1.open remmina 
2.close 
3.click icon on tray
4.fail to open again

#### MATE general version
none

#### Package version

none
#### Linux Distribution

none

**Comment by raveit65** [comment]
remmina ? 
wrong repository.

**Comment by raveit65** [comment]
https://github.com/FreeRDP/Remmina
