### ISSUE TITLE
Character Encoding combo box doesn't show an initial selection

### ISSUE THREAD

**Issue by LogicFinity** [mate-desktop/pluma#703]
#### Expected behaviour

In the Open Files dialog box, the Character Encoding combo box shows the initially selected Character Encoding selection, "Automatically Detected".

#### Actual behaviour

The Character Encoding combo box doesn't show that anything is selected. In earlier versions of pluma (confirmed on Devuan Jessie, pluma 1.8.1), the combo box defaults to the first choice "Automatically Detected". Internally, the first choice IS selected, but the GUI doesn't show it.

#### Steps to reproduce the behaviour

  - Launch the pluma text editor.
  - File -> Open
  - Look at the Character Encoding combo box.

#### MATE general version

MATE Desktop Environment 1.26.0

Other lib versions:

X version: 1.7.7
gtk version: gtk 3.24.38
glib version: 2.74.6
mate lib version: 1.26
libC version: 2.39

#### Package version

1.26.0-1+deb12u

#### Linux Distribution

Devuan Daedalus (based on Debian Bookworm version 12)

#### Link to bugreport of your Distribution (requirement)

I haven't figured out how to file a bug in Debian Bookworm yet.

#### My analysis

The problem occurs in "pluma/pluma-encodings-combo-box.c". The combo box contents and initial selection are initialized in the instance constructor pluma_encodings_combo_box_init(). For whatever reason, if you set the combox selection in this constructor, although it IS selected internally, the GUI doesn't redraw and show the selected item.

The initialization code logic hasn't changed from pluma 1.8.1 to 1.26. I suspect the problem is caused by gtk-3 initializing the combo box differently than gtk-2.

#### My proposed fix

I looked at gedit 44.2, and their Character Encoding combo box does NOT have this problem. That's because in their code, they moved the initialization into a "constructed" function. This proposal is based on their fix.

- Define the constructed callback function:

```
    static void
    pluma_encodings_combo_box_constructed (GObject *object)
    {
        PlumaEncodingsComboBox *combo = PLUMA_ENCODINGS_COMBO_BOX (object);
        GtkCellRenderer *text_renderer;

        G_OBJECT_CLASS (pluma_encodings_combo_box_parent_class)->constructed (object);

	    /* Setup up the cells */
	    text_renderer = gtk_cell_renderer_text_new ();
	    gtk_cell_layout_pack_end (GTK_CELL_LAYOUT (combo),
				      text_renderer, TRUE);

	    gtk_cell_layout_set_attributes (GTK_CELL_LAYOUT (combo),
					    text_renderer,
					    "text",
					    NAME_COLUMN,
					    NULL);

        update_menu (combo);
    }

```
- pluma_encodings_combo_box_class_init: Set up the constructed callback function.

`        object_class->constructed = pluma_encodings_combo_box_constructed;`

  - Result:

```
    static void
    pluma_encodings_combo_box_class_init (PlumaEncodingsComboBoxClass *klass)
    {
	    GObjectClass *object_class = G_OBJECT_CLASS (klass);

	    object_class->set_property = pluma_encodings_combo_box_set_property;
	    object_class->get_property = pluma_encodings_combo_box_get_property;
	    object_class->dispose = pluma_encodings_combo_box_dispose;
	    object_class->constructed = pluma_encodings_combo_box_constructed;

	    g_object_class_install_property (object_class,
					     PROP_SAVE_MODE,
					     g_param_spec_boolean ("save-mode",
							           "Save Mode",
							           "Save Mode",
							           FALSE,
							           G_PARAM_READWRITE |
							           G_PARAM_CONSTRUCT |
							           G_PARAM_STATIC_STRINGS));
    }

```
* pluma_encodings_combo_box_init: Delete the lines that were moved into the constructed callback function.

```
	GtkCellRenderer *text_renderer;

    <...>

	/* Setup up the cells */
	text_renderer = gtk_cell_renderer_text_new ();
	gtk_cell_layout_pack_end (GTK_CELL_LAYOUT (menu),
				  text_renderer, TRUE);

	gtk_cell_layout_set_attributes (GTK_CELL_LAYOUT (menu),
					text_renderer,
					"text",
					NAME_COLUMN,
					NULL);

	<...>

	update_menu (menu);

```
  - Result:

```
    static void
    pluma_encodings_combo_box_init (PlumaEncodingsComboBox *menu)
    {
	    menu->priv = pluma_encodings_combo_box_get_instance_private (menu);

	    menu->priv->enc_settings = g_settings_new (PLUMA_SCHEMA_ID);

	    menu->priv->store = gtk_list_store_new (N_COLUMNS,
						    G_TYPE_STRING,
						    G_TYPE_POINTER,
						    G_TYPE_BOOLEAN);

	    gtk_combo_box_set_row_separator_func (GTK_COMBO_BOX (menu),
					          separator_func, NULL,
					          NULL);

	    menu->priv->changed_id = g_signal_connect (menu, "changed",
						       G_CALLBACK (add_or_remove),
						       menu->priv->store);
    }

```
#### Side effects of my proposed fix

This code change also fixes a problem that goes as far back as gedit 2.30.3 (before pluma was forked). There are 3 places where this Character Encoding combo box is used:

  - File -> Open
  - File -> Save As
  - Error opening a file (example, when opening a binary file).

The combo box item "Automatically Detected" was only supposed to appear in File -> Open, and not the other two cases. The property "save_mode" is used to decide whether or not to add the "Automatically Detected" selection.

The problem is that inside the constructor pluma_encodings_combo_box_init(), the property "save_mode" has NOT been set yet. That is, pluma_encodings_combo_box_set_property() is not yet called to initialize the combo box properties. So the save_mode is ALWAYS 0, and the item "Automatically Detected" is ALWAYS added.

With this proposed fix, the "Automatically Detected" selection is displayed ONLY for File -> Open, as the code originally intended.

#### My final thoughts

If I can figure out how to make a pull request, I'll convert my proposed fix into a pull request.

**Comment by lukefromdc** [comment]
I just converted this to a PR myself, thanks! Worked perfectly in my test and confirmed both the issue and the fix
https://github.com/mate-desktop/pluma/pull/704

**Comment by LogicFinity** [comment]
Thanks for making the pull request. I don't know if you still need this info, but I did figure out how to file a Debian bug:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1089560

**Comment by lukefromdc** [comment]
Thanks for doing so, that so often gets ignored. The reason my own bug reports don't contain this is only because all of my MATE packages are locally compiled. Distro-specific issues are not uncommon at all.
