### ISSUE TITLE
please add option to enable "Autocheck Spelling" by default

### ISSUE THREAD

**Issue by IndichRMV** [mate-desktop/pluma#90]
It's frustrating for me to have to enable this option on a case-by-case basis -- I would prefer for spelling errors to be highlighted by default.

The current behaviour is that this setting is remembered per-document, which doesn't make any sense to me -- this is what the Gnome developers implemented when users requested this change; of course, I'm not aware of anyone who was happy with that. See https://bugzilla.gnome.org/show_bug.cgi?id=305055

**Comment by monsta** [comment]
https://github.com/mate-desktop/pluma/issues/146 is merged, so this request is filled.
