### ISSUE TITLE
Middle click paste not working Pluma

### ISSUE THREAD

**Issue by juanfgs** [mate-desktop/pluma#92]
Yhis is one that has been around since Gnome 2.8 or 2.10 I think and never got fixed, middle click pasting on pluma doesn't work (gedit 3 even inherited this bug), it works on all other GTK2 editors, Geany, mousepad, you name it, just pluma and gedit.

Steps to reproduce: select some text, go to pluma window and click the middle button in the text area. The text doesn't get pasted.

Tested on version 1.8.1 on Fedora 20 ( NVidia drivers)

**Comment by monsta** [comment]
Works fine in Pluma 1.11. I can paste a selection from other apps and from Pluma itself.

If nobody confirms it in latest versions I'll close this issue as fixed.

**Comment by raveit65** [comment]
closed because f20 is EOL, should work with 1.10

**Comment by jzakrzewski** [comment]
I'm on Ubuntu MATE with Pluma 1.12.2 and no - it doesn't work.

* I can select in Pluma and paste somewhere else
* I can select somewhere else and paste in Pluma
* I cannot select in Pluma and paste it there. Additionally, if I try, the X-clipboard gets cleared.

**Comment by Yasen6275** [comment]
Fedora 28 pluma 1.20.4-1

- I can select in Pluma and paste somewhere else
- I can select somewhere else and paste in Pluma
- I cannot select in Pluma and paste it there. Additionally, if I try, the X-clipboard gets cleared.

**Comment by lukefromdc** [comment]
1.12 is a very old version, some time ago we fixed an issue related to this, and had to include a gsettings key because for some users (such as myself) the re-introduction of middle click paste created problems.
