### ISSUE TITLE
find dialog a little slow to come up first time after starting pluma

### ISSUE THREAD

**Issue by Heith1968** [mate-desktop/pluma#94]
After opening pluma, the first time the user brings up the Find dialog (either by pressing Ctrl-F or going to Search->Find) it takes a good 1.5 seconds to come up on my computer. I know it doesn't sound like much, but it disrupts my workflow ... actually I'm so used to application find features coming up near-instantly that I begin typing my query after maybe 0.5 seconds, and that text ends up going into the document ... so I have to stop and undo the inadvertent change before going back to enter my query into the Find dialog.

After this first time, the Find dialog comes up instantly for any subsequent uses. Would it be possible to preload the find dialog when Pluma starts to prevent the lag the first time it's brought up?

**Comment by monsta** [comment]
Doesn't look slow in the latest versions. Do you still get this?

**Comment by monsta** [comment]
Oops, wrong button :smile:

**Comment by Heith1968-2** [comment]
yes, this looks good in current version. you can close the bug.
