### ISSUE TITLE
Pluma is spelled pluma under some circumstances

### ISSUE THREAD

**Issue by FuzzyToothpaste** [mate-desktop/pluma#96]
Occasionally, Pluma will be spelled pluma in the GUI. The only instance of this that I've noticed is in the Help - About dialog where it says "pluma is a small and lightweight text editor for the MATE Desktop".

**Comment by FuzzyToothpaste** [comment]
This makes me wonder what the proper spelling of Pluma even is. I see Pluma and pluma used interchangeably in the program, source code, and even the website and documentation.

**Comment by infirit** [comment]
The correct name is Pluma with a capital P.

**Comment by monsta** [comment]
Fixed that in About dialog in https://github.com/mate-desktop/pluma/commit/8c43c2cfdc87ecbc0058f319012e3c61e31d1629. Any other places without capitalization left? If not, we can close this issue.

**Comment by FuzzyToothpaste** [comment]
You should fix it in the title of the window if that hasn't been done already (I can't test trunk myself), but other than that we should be all good.

**Comment by monsta** [comment]
- fixed titles of main window and prefs window in https://github.com/mate-desktop/pluma/commit/4299e647a7e13118b129266e914fec2a833c44b7
- fixed title of Run command plugin dialog in https://github.com/mate-desktop/pluma/commit/ab4da31e0815c8c7931c7075d7b7c54c6666106e

Hope that's all :smile:
